facebook/FBSimulatorControl

FBSimulatorControl.xcodeproj/project.pbxproj

Expose the headers to enable framework users to use the classes in this framework. This PR only exposes those headers whose name starts with FB.
Also it would be nice to have an umbrella header but the FBSimulatorControl header is already taken by a class.

Expose headers

---

FBSimulatorControl.xcodeproj/project.pbxproj
FBSimulatorControl/Management/FBSimulatorPool.m
FBSimulatorControlTests/Tests/FBSimulatorPoolAllocationTests.m

When running allocation/deletion repeatedly, it's possible to expose what looks to be [`-[SimDeviceSet deleteDevice:error:]`](https://github.com/facebook/FBSimulatorControl/blob/master/PrivateHeaders/CoreSimulator/SimDeviceSet.h#L37) returning too early. 
I've managed to reproduce frequent failure of the new `-[FBSimulatorPoolAllocationTests testRemovesDeletedDeviceFromSet]` test, which can also be exposed in the startup path of `FBSimulatorControl`.
Instead of relying on the `SimDeviceSet` API doing the right thing, we can block on the existence of the newly-deleted Simulator in the DeviceSet and fail if this times out.

Guard against races in Simulator deletion

---

FBSimulatorControl.xcodeproj/project.pbxproj
FBSimulatorControl/Configuration/FBSimulatorControlConfiguration.h
FBSimulatorControl/Configuration/FBSimulatorControlConfiguration.m
FBSimulatorControl/Management/FBSimulatorPool+Private.h
FBSimulatorControl/Management/FBSimulatorPool.m
FBSimulatorControlTests/Tests/FBProcessLaunchConfigurationTests.m
FBSimulatorControlTests/Tests/FBSimulatorControlApplicationLaunchTests.m
FBSimulatorControlTests/Tests/FBSimulatorControlConfigurationTests.m
FBSimulatorControlTests/Tests/FBSimulatorControlSimulatorLaunchTests.m
FBSimulatorControlTests/Tests/FBSimulatorPoolAllocationTests.m
FBSimulatorControlTests/Tests/FBSimulatorPoolTests.m

Adds an additional property to `FBSimulatorControlConfiguration` to allow for prefixes other than `E2E`. A prefix *must* be non-empty for the meantime, until it is possible to work this out with a separately managed `SimDeviceSet`.

Configurable prefix for Pool-Managed Simulators

---

FBSimulatorControl/Management/FBSimulatorPool.m
FBSimulatorControlTests/Tests/FBSimulatorPoolAllocationTests.m

#14 waited on Simulators to actually be removed from the `SimDeviceSet` before returning from a deletion method, however this wasn't used in the batch deletion method `-[FBSimulatorPool deleteSimulators:withError:]. This PR fixes that.

Fix batched-deletion SimDevices sticking around

---

FBSimulatorControl/Management/FBSimulatorPool.m
FBSimulatorControl/Utility/NSRunLoop+SimulatorControlAdditions.h
FBSimulatorControl/Utility/NSRunLoop+SimulatorControlAdditions.m

We probably waste a lot of time waiting on conditions that resolve very quickly. Instead of waiting for this every second we can still be prudent in terms of system resources (by not checking the condition continuously) but also resolve conditions faster by setting this to 100ms instead

Increase runloop spin frequency

---

FBSimulatorControl.xcodeproj/project.pbxproj
FBSimulatorControl/Management/FBSimulatorPool.m
FBSimulatorControl/Utility/NSRunLoop+SimulatorControlAdditions.h
FBSimulatorControl/Utility/NSRunLoop+SimulatorControlAdditions.m
FBSimulatorControlTests/Tests/FBSimulatorSessionLifecycleTests.m

In #10 @arpadzalan was looking for a way to assert that some process dies in order to terminate the test. This adds a test for an unexpected Application Notification.

Add test for unexpected application termination notifications

---

FBSimulatorControl/Management/FBSimulator+Private.h
FBSimulatorControl/Management/FBSimulator.h
FBSimulatorControl/Management/FBSimulator.m
FBSimulatorControl/Management/FBSimulatorControl.m
FBSimulatorControl/Management/FBSimulatorPool+Private.h
FBSimulatorControl/Management/FBSimulatorPool.h
FBSimulatorControl/Management/FBSimulatorPool.m
FBSimulatorControl/Session/FBSimulatorSession+Private.h
FBSimulatorControl/Session/FBSimulatorSession.h
FBSimulatorControl/Session/FBSimulatorSession.m
FBSimulatorControlTests/Tests/FBSimulatorPoolAllocationTests.m
FBSimulatorControlTests/Tests/FBSimulatorPoolTests.m

Extracts out `FBSimulator` simulator behavior to allow all Simulators to be wrapped with the `FBSimulator` conveniences that are relevant, regardless of whether they are managed or unmanaged.
A Concreted subclass `FBManagedSimulator` deals with allocation/freeing of these Simulators. This improves a lot of the inflation of `SimDevice` to `FBSimulator` and means that `FBSimulatorPool` spends a lot less time dealing with heterogeneous objects.
This also means that expensive information about a simulator (for example the construction of processes that have been created through `launchd_sim`) can be done lazily and will apply to any simulator, not just 'managed' ones.

Managed & Unmanaged FBSimulator

---

FBSimulatorControl.xcodeproj/project.pbxproj
FBSimulatorControl/Management/FBSimulatorInteraction+Private.h
FBSimulatorControl/Management/FBSimulatorInteraction.h
FBSimulatorControl/Management/FBSimulatorInteraction.m
FBSimulatorControl/Session/FBSimulatorSessionInteraction+Private.h
FBSimulatorControl/Session/FBSimulatorSessionInteraction.h
FBSimulatorControl/Session/FBSimulatorSessionInteraction.m
FBSimulatorControl/Utility/FBInteraction+Private.h
FBSimulatorControl/Utility/FBInteraction.h
FBSimulatorControl/Utility/FBInteraction.m

`FBSimulatorInteraction` and `FBSimulatorSessionInteraction` have common behavior, but duplicate implementations of some methods. 
This PR extracts the common behaviour, also giving `FBSimulatorInteraction` retrying.

Extract Interactions to base class

---

FBSimulatorControl.xcodeproj/project.pbxproj
FBSimulatorControl/Configuration/FBSimulatorConfiguration+Convenience.m
FBSimulatorControl/Configuration/FBSimulatorConfiguration+CoreSimulator.h
FBSimulatorControl/Configuration/FBSimulatorConfiguration+CoreSimulator.m
FBSimulatorControl/Configuration/FBSimulatorConfiguration+Private.h
FBSimulatorControl/Configuration/FBSimulatorConfiguration.h
FBSimulatorControl/Configuration/FBSimulatorConfiguration.m
FBSimulatorControl/Management/FBSimulator+Private.h
FBSimulatorControl/Management/FBSimulator.h
FBSimulatorControl/Management/FBSimulator.m
FBSimulatorControl/Management/FBSimulatorPool.m
FBSimulatorControl/Session/FBSimulatorSessionInteraction.m

When launching Simulators, it can be useful to set the scale to a more appropriate one depending on the desktop resolution of the machine launching the Simulator. 
This PR adds this into the configuration, with a default value and the necessary plumbing to fix this value via the Command Line to Simulator.app.

Add Scale to Simulator Configuration

---

FBSimulatorControl.xcodeproj/project.pbxproj
FBSimulatorControl/Management/FBSimulator+Queries.h
FBSimulatorControl/Management/FBSimulator+Queries.m
FBSimulatorControl/Management/FBSimulator.h
FBSimulatorControl/Management/FBSimulator.m
FBSimulatorControl/Session/FBSimulatorSessionLifecycle.m
FBSimulatorControlTests/Tests/FBSimulatorControlSimulatorLaunchTests.m
FBSimulatorControlTests/Tests/FBSimulatorTests.m

The Process Identifier of a `FBSimulator` can be inferred from the arguments of the launched Simulator process. This allows `FBSimulatorControl` to use the PID to find the Windows of Simulator Applications that *haven't* been launched by the *current `FBSimulatorControl` process*.
Also added a test to confirm this.

Add inference of Simulator Process Identifiers

---

FBSimulatorControl.xcodeproj/project.pbxproj
FBSimulatorControl/Management/FBSimulatorPool.h
FBSimulatorControl/Management/FBSimulatorPool.m
FBSimulatorControl/Management/FBSimulatorPredicates.h
FBSimulatorControl/Management/FBSimulatorPredicates.m
FBSimulatorControlTests/Tests/FBSimulatorPoolTests.m

Extracts out the filtering of the `allSimulators` property of `FBSimulatorPool` into discrete `NSPredicate` objects in the `FBSimulatorPredicates` object. Thanks to `NSCompoundPredicate` it should become easier to define more complex filtering of Simulators.
By using #25 it should be possible to get a collection of Process Identifiers of *any* `FBSimulatorControl` launched Simulator, regardless of the process that it was launched from.
Copy of #26 but into master instead.

Composable NSPredicates for finding Simulators

---

FBSimulatorControl.xcodeproj/project.pbxproj
FBSimulatorControl/Session/FBSimulatorSessionInteraction.h
FBSimulatorControl/Session/FBSimulatorSessionInteraction.m
FBSimulatorControl/Tiling/FBSimulatorWindowHelpers.h
FBSimulatorControl/Tiling/FBSimulatorWindowHelpers.m
FBSimulatorControl/Tiling/FBSimulatorWindowTiler.h
FBSimulatorControl/Tiling/FBSimulatorWindowTiler.m
FBSimulatorControl/Utility/FBSimulatorError.h
FBSimulatorControl/Utility/FBSimulatorError.m
FBSimulatorControlTests/Tests/FBSimulatorWindowTilingTests.m

Using the Mac OS X Accessibility APIs, it's possible to tile the windows so that they are in the foreground and do not overlap each other. This makes observing the windows in an automated fashion substantially easier.
Adds a test to this effect.

Add Window Tiling

---

FBSimulatorControl.xcodeproj/project.pbxproj
FBSimulatorControl/Session/FBSimulatorSession.h
FBSimulatorControl/Session/FBSimulatorSessionInteraction.h
FBSimulatorControl/Session/FBSimulatorSessionInteraction.m
FBSimulatorControl/Session/FBSimulatorSessionLifecycle.h
FBSimulatorControl/Session/FBSimulatorSessionLifecycle.m
FBSimulatorControl/Session/FBSimulatorSessionState+Private.h
FBSimulatorControl/Session/FBSimulatorSessionState+Queries.h
FBSimulatorControl/Session/FBSimulatorSessionState+Queries.m
FBSimulatorControl/Session/FBSimulatorSessionState.h
FBSimulatorControl/Session/FBSimulatorSessionState.m
FBSimulatorControl/Session/FBSimulatorSessionStateGenerator.h
FBSimulatorControl/Session/FBSimulatorSessionStateGenerator.m
FBSimulatorControl/Tiling/FBSimulatorWindowHelpers.h
FBSimulatorControl/Tiling/FBSimulatorWindowHelpers.m
FBSimulatorControl/Tiling/FBSimulatorWindowTiler.h
FBSimulatorControl/Tiling/FBSimulatorWindowTiler.m
FBSimulatorControl/Utility/FBSimulatorError.h
FBSimulatorControl/Utility/FBSimulatorError.m
FBSimulatorControlTests/Tests/FBSimulatorStateTests.m
FBSimulatorControlTests/Tests/FBSimulatorWindowTilingTests.m

It makes some sense to have a sense of Diagnostics for an entire Session. Not all diagnostics should be restricted to a process launched by the User. This allows System processes and other Simulator-specific diagnostic information to be associated with an entire test-run for example.
Depends on #23.

Session state diagnostics

---

FBSimulatorControl.xcodeproj/project.pbxproj
FBSimulatorControl/Session/FBSimulatorSessionInteraction.h
FBSimulatorControl/Session/FBSimulatorSessionInteraction.m
FBSimulatorControl/Video/FBSimulatorVideoRecorder.h
FBSimulatorControl/Video/FBSimulatorVideoRecorder.m
FBSimulatorControlTests/Tests/FBSimulatorVideoRecorderTests.m

Builds on the work #29 and #23 to use `AVCaptureScreenInput` to record a video of multiple Simulators at once, to separate files.

Video Recording

---

FBSimulatorControl.xcodeproj/project.pbxproj
FBSimulatorControl/Session/FBSimulatorSessionInteraction.h
FBSimulatorControl/Session/FBSimulatorSessionInteraction.m
FBSimulatorControl/Tiling/FBSimulatorWindowHelpers.m
FBSimulatorControl/Tiling/FBSimulatorWindowTiler.h
FBSimulatorControl/Tiling/FBSimulatorWindowTiler.m
FBSimulatorControl/Tiling/FBSimulatorWindowTilingStrategy.h
FBSimulatorControl/Tiling/FBSimulatorWindowTilingStrategy.m
FBSimulatorControlTests/Tests/FBSimulatorTilingStrategyTests.m
FBSimulatorControlTests/Tests/FBSimulatorWindowTilingTests.m

There's more than one way of tiling windows within the Display bounds, so this should be pulled out into a strategy that defines the interface for interacting with other windows. 
For example, it may be possible to guarantee a maximum number of simulators, so offsetting in regions of a display is good enough.
Later, it may make sense to be able to compose these strategies. For example, there could be multiple tests in parallel with multiple simulators per-test. In this case the tests could be tiled horizontally and vertical tiling for the simulators within a test.

Add Window Tiling Strategies

---

FBSimulatorControl.xcodeproj/project.pbxproj
FBSimulatorControlTests/Tests/FBSimulatorControlApplicationLaunchTests.m
FBSimulatorControlTests/Tests/FBSimulatorControlSimulatorLaunchTests.m
FBSimulatorControlTests/Tests/FBSimulatorPoolAllocationTests.m
FBSimulatorControlTests/Tests/FBSimulatorSessionLifecycleTests.m
FBSimulatorControlTests/Tests/FBSimulatorTests.m
FBSimulatorControlTests/Tests/FBSimulatorVideoRecorderTests.m
FBSimulatorControlTests/Tests/FBSimulatorWindowTilingTests.m
FBSimulatorControlTests/Utilities/FBSimulatorControlTestCase.h
FBSimulatorControlTests/Utilities/FBSimulatorControlTestCase.m

Moves a lot of the duplicated code for creating `FBSimulatorControl` to a `XCTestCase` subclass. Drastically reduces the amount of boiler plate and provides a common way of cleaning up `FBSimulator` instances after they have been allocated by a Test Case.

Base XCTestCase

---

FBSimulatorControl/Configuration/FBProcessLaunchConfiguration+Helpers.h
FBSimulatorControl/Configuration/FBProcessLaunchConfiguration+Helpers.m

WDA doesn't exist in the bundle from which it is fetched (the `FBSimulatorControl.framework`), it doesn't make much sense to have this here.
We can replace this with better documentation and samples. There is no `WebDriverAgent` binary artifact  here yet.

Remove WDA Helper

---

FBSimulatorControl/Configuration/FBSimulatorControlConfiguration.h
FBSimulatorControl/Configuration/FBSimulatorControlConfiguration.m
FBSimulatorControl/Configuration/FBSimulatorControlStaticConfiguration.h
FBSimulatorControl/Configuration/FBSimulatorControlStaticConfiguration.m
FBSimulatorControl/Management/FBSimulatorControl.m
FBSimulatorControl/Session/FBSimulatorSessionInteraction.m
FBSimulatorControlTests/Tests/FBSimulatorControlConfigurationTests.m
FBSimulatorControlTests/Tests/FBSimulatorControlSimulatorLaunchTests.m
FBSimulatorControlTests/Tests/FBSimulatorPoolAllocationTests.m
FBSimulatorControlTests/Tests/FBSimulatorPoolTests.m
FBSimulatorControlTests/Utilities/FBSimulatorControlTestCase.h
FBSimulatorControlTests/Utilities/FBSimulatorControlTestCase.m

It's possible to change `Simulator.app` to use a different device set by passing `-DeviceSetPath` as an arg to the launched `Simulator`. This will be vastly preferable to using Prefixes to isolate simulators between processes.
cc @mmmulani @ExtremeMan

Support Custom SimDeviceSets

---

FBSimulatorControl/Session/FBSimulatorSessionInteraction.m
FBSimulatorControl/Utility/FBSimulatorError.h
FBSimulatorControl/Utility/FBSimulatorError.m

Adds some preconditions for interactions in the form of Assertions or Errors:
- Assertions for Progammer Error: nil values passed to methods
- Errors for when the Simulator is not in a state to perform an interaction: can't run an app if it isn't installed

Preconditions for Session Interactions

---

FBSimulatorControl/Configuration/FBSimulatorControlConfiguration.h
FBSimulatorControl/Configuration/FBSimulatorControlConfiguration.m
FBSimulatorControl/Management/FBSimulator+Private.h
FBSimulatorControl/Management/FBSimulator.h
FBSimulatorControl/Management/FBSimulator.m
FBSimulatorControl/Management/FBSimulatorControl+Private.h
FBSimulatorControl/Management/FBSimulatorControl.m
FBSimulatorControl/Management/FBSimulatorPool.h
FBSimulatorControl/Management/FBSimulatorPool.m
FBSimulatorControl/Management/FBSimulatorPredicates.h
FBSimulatorControl/Management/FBSimulatorPredicates.m
FBSimulatorControl/Session/FBSimulatorSession+Private.h
FBSimulatorControl/Session/FBSimulatorSession.h
FBSimulatorControl/Session/FBSimulatorSession.m
FBSimulatorControl/Session/FBSimulatorSessionInteraction.m
FBSimulatorControlTests/Tests/FBSimulatorControlConfigurationTests.m
FBSimulatorControlTests/Tests/FBSimulatorPoolAllocationTests.m
FBSimulatorControlTests/Tests/FBSimulatorPoolTests.m
FBSimulatorControlTests/Tests/FBSimulatorStateTests.m
FBSimulatorControlTests/Utilities/FBSimulatorControlNotificationAssertion.m
FBSimulatorControlTests/Utilities/FBSimulatorControlTestCase.h
FBSimulatorControlTests/Utilities/FBSimulatorControlTestCase.m
README.md

`SimDeviceSets` are a far superior way of ensuring that Simulators are segregated and put elsewhere. Removing the concept of a 'Managed' Simulator vastly simplifies the allocation process and means that the default device set doesn't get littered with Simulators. This will also allow other tools to use `FBSimulatorControl` to manipulate Simulators that were created externally from `FBSimulatorControl`

Remove Managed/Unmanaged Simulator Distinction

---

FBSimulatorControl/Configuration/FBSimulatorConfiguration+Private.h
FBSimulatorControl/Configuration/FBSimulatorConfiguration.m

Adds the new Device Specs for 7.1 as well as the 9.1 runtime. Also adds a more sensible way of finding the default OS Version so that there's not unnecessary crashing.

Fixes for Xcode 7.1

---

FBSimulatorControl/Logs/FBWritableLog.h
FBSimulatorControl/Logs/FBWritableLog.m

Depending on the backing-store of the log data there is an optimal way of figuring out whether there is any content or not. `hasLogContent` is used in preference to `isEmpty` as this allows checking for the existence of a writable log & it's data in one method call (msgsend to nil).

Add query for existence of log data to FBWritableLog

---

FBSimulatorControl/Configuration/FBSimulatorControlConfiguration.h
FBSimulatorControl/Management/FBSimulator.h
FBSimulatorControl/Management/FBSimulator.m
FBSimulatorControl/Management/FBSimulatorControl.m
FBSimulatorControl/Management/FBSimulatorPool.m
FBSimulatorControlTests/Utilities/FBSimulatorControlTestCase.m

Instead of building up a massive list of simulators to kill using `grep -e` based upon the contents of the `DeviceSet` it's easier to just kill all using the path to the `SimDeviceSet` in the params as this will always be passed. The same applies to Simulators launched without a DeviceSet, which just searches based upon the existence of `CurrentDeviceUDID`.

Improve robustness of killAll in DeviceSet

---

FBSimulatorControl/Utility/FBInteraction.h
FBSimulatorControl/Utility/FBInteraction.m

Some interactions are optional and can therefore be modified in a similar way to `retry:` to prevent unnecessary failure.

Ignorable Interaction Failure

---

FBSimulatorControl/Management/FBSimulatorInteraction.m
FBSimulatorControl/Session/FBSimulatorSessionInteraction.m
FBSimulatorControl/Utility/FBInteraction+Private.h
FBSimulatorControl/Utility/FBInteraction.h
FBSimulatorControl/Utility/FBInteraction.m

Chaining interactions from *inside* an `interact:` block is hard since it requires capture of `self`, where `self` is an interaction subclass. Instead of requiring all `interact:` blocks to manually avoid self capture, the implementation can just pass a `weak`ed `self`

Pass interaction to interact

---

FBSimulatorControl/Logs/FBSimulatorLogs.h
FBSimulatorControl/Logs/FBSimulatorLogs.m
FBSimulatorControl/Logs/FBWritableLog.m
FBSimulatorControl/Session/FBSimulatorSessionInteraction.m
FBSimulatorControl/Session/FBSimulatorSessionState+Queries.h
FBSimulatorControl/Session/FBSimulatorSessionState+Queries.m
FBSimulatorControl/Session/FBSimulatorSessionStateGenerator.m
FBSimulatorControl/Tasks/FBTask+Private.h
FBSimulatorControl/Tasks/FBTask.h
FBSimulatorControl/Tasks/FBTask.m
FBSimulatorControlTests/Tests/FBSimulatorLogsTests.m
FBSimulatorControlTests/Tests/FBSimulatorSessionLifecycleTests.m

Adds provisional support for bucketing the syslog by launched processes, using the process identifier of previously launched processes. This is pretty suboptimal at the moment and it should be possible to improve upon this with `asl` or `syslog` in the future. 
There were some changes that needed to be made in file handling for `FBTask` so this was updated also.

Add Logs for Launched Processes

---

FBSimulatorControl.xcodeproj/project.pbxproj
FBSimulatorControl/Configuration/FBSimulatorControlConfiguration.h
FBSimulatorControl/Management/FBSimulator.h
FBSimulatorControl/Management/FBSimulator.m
FBSimulatorControl/Management/FBSimulatorPool.m
FBSimulatorControl/Management/FBSimulatorTerminationStrategy.h
FBSimulatorControl/Management/FBSimulatorTerminationStrategy.m

Terminating Simulators is Hard™. This pulls out the nuts-and-bolts to a separate `FBSimulatorTerminationStrategy` class. The immediate effect is that `FBSimulatorPool` has a smaller footprint. Longer-term I'd like to look at using `sysctl` and `NSWorkspace` to terminate simulators in a more reasonable way.

Add FBSimulatorTerminationStrategy

---

.gitignore
FBSimulatorControl.xcodeproj/project.pbxproj
FBSimulatorControl/Management/FBSimulatorControl+Class.h
FBSimulatorControl/Management/FBSimulatorControl.h
FBSimulatorControl/Management/FBSimulatorControl.m
FBSimulatorControlTests/Fixtures/FBSimulatorControlFixtures.m
FBSimulatorControlTests/Tests/FBProcessLaunchConfigurationTests.m
FBSimulatorControlTests/Tests/FBSimulatorApplicationTests.m
FBSimulatorControlTests/Tests/FBSimulatorControlApplicationLaunchTests.m
FBSimulatorControlTests/Tests/FBSimulatorControlConfigurationTests.m
FBSimulatorControlTests/Tests/FBSimulatorControlSimulatorLaunchTests.m
FBSimulatorControlTests/Tests/FBSimulatorLogsTests.m
FBSimulatorControlTests/Tests/FBSimulatorPoolAllocationTests.m
FBSimulatorControlTests/Tests/FBSimulatorSessionInteractionTests.m
FBSimulatorControlTests/Tests/FBSimulatorSessionLifecycleTests.m
FBSimulatorControlTests/Tests/FBSimulatorStateTests.m
FBSimulatorControlTests/Tests/FBSimulatorTests.m
FBSimulatorControlTests/Tests/FBSimulatorTilingStrategyTests.m
FBSimulatorControlTests/Tests/FBSimulatorVideoRecorderTests.m
FBSimulatorControlTests/Tests/FBSimulatorWindowTilingTests.m
FBSimulatorControlTests/Tests/FBTaskExecutorTests.m
FBSimulatorControlTests/Tests/FBWritableLogTests.m

Creates an Umbrella Header so that consumers of `FBSimulatorControl` can easily import all the good stuff. Creates a Module Map so that `FBSimulatorControl` can be used from Swift.
All headers `#import` with Framework Import style.

Umbrella Header

---

FBSimulatorControl/Management/FBSimulatorPredicates.h
FBSimulatorControl/Management/FBSimulatorPredicates.m
fbsimctl/Sources/Arguments.swift
fbsimctl/Sources/Bridging.swift
fbsimctl/Sources/Command.swift
fbsimctl/Sources/Constants.h
fbsimctl/Sources/Constants.m
fbsimctl/Sources/Help.swift
fbsimctl/Sources/LineBuffer.swift
fbsimctl/Sources/Parsers.swift
fbsimctl/Sources/Relay.swift
fbsimctl/Sources/Runners.swift
fbsimctl/Sources/SignalHandler.swift
fbsimctl/Sources/SocketRelay.swift
fbsimctl/Sources/StdIORelay.swift
fbsimctl/Sources/fbsimctl-Bridging-Header.h
fbsimctl/Sources/main.swift
fbsimctl/fbsimctl.xcodeproj/project.pbxproj
fbsimctl/fbsimctl.xcodeproj/xcshareddata/xcschemes/fbsimctl.xcscheme
fbsimctl/fbsimctl.xcworkspace/contents.xcworkspacedata

This PR adds a commandline called `fbsimctl` to the repo, by using the `FBSimulatorControl.framework` from a separate workspace. It is a Swift-based mac CLI that aims to expose a bunch of the features in a way that doesn't require directly require interfacing with the framework. In is intended to be extended in the future and to do many of the things that `simctl` doesn't.

Add fbsimctl

---

FBSimulatorControl/Management/FBSimulatorPool.h
FBSimulatorControl/Management/FBSimulatorPool.m

Added this as a C method because I couldn't find any good class that made sense for this.
Put it in the FBSimulatorPool header because that seems like the best place for it.

Add option to enable CoreSimulator logging

---

FBSimulatorControl/Configuration/FBSimulatorControlStaticConfiguration.h
FBSimulatorControl/Configuration/FBSimulatorControlStaticConfiguration.m
FBSimulatorControl/Management/FBSimulatorTerminationStrategy.h
FBSimulatorControl/Management/FBSimulatorTerminationStrategy.m
FBSimulatorControl/Session/FBSimulatorSessionInteraction.m
FBSimulatorControl/Utility/FBProcessQuery.m

Updates `FBSimulatorTerminationStrategy` to not be terrible anymore and use `FBProcessQuery` directly. This should make it substantially easier to maintain and vastly simplifies the code. I would expect performance is better in the startup path now as a bunch of syscalls are going to be a lot faster than subshelling out multiple times (with each subshell process making a bunch of syscalls).
Now that we know about the environment of launched `Simulator.app` processes it's also easier to determine which processes were launched by `FBSimulatorControl` by inserting a :tophat: magic :tophat: string into the environment. This is better than using arguments to the process, since we can't reasonably assume they will be ignored in the implementation of the Simulator Application.

Remove prgep usage from FBSimulatorTerminationStrategy

---

FBSimulatorControl/Management/FBSimulator+Queries.m
FBSimulatorControl/Utility/FBProcessQuery.h
FBSimulatorControl/Utility/FBProcessQuery.m

Searching for `launchd_sim` by using paths is not performant and far too complicated than it needs to be. Finding the open processes for a file path is also orders of magnitude slower than getting simulator by launch path. It's also possible to optimise `processesWithLaunchPathSubstring:` later since `libproc` can provide all of them without the need for multiple syscalls.
Fortunately there are plenty of arguments and environment variables in the `launchd_sim` process that do contain the UDID of the Simulator, so we can use those instead.

More performant search for launchd_sim

---

FBSimulatorControlTests/Tests/FBSimulatorLogsTests.m
FBSimulatorControlTests/Tests/FBTaskExecutorTests.m
FBSimulatorControlTests/Utilities/FBSimulatorControlAssertions.h
FBSimulatorControlTests/Utilities/FBSimulatorControlAssertions.m

Current messages in CI are pretty bad for substring match failure.

More helpful failure messages for substring matching

---

FBSimulatorControl/Configuration/FBSimulatorControlConfiguration.h
FBSimulatorControl/Management/FBSimulatorPool.m
FBSimulatorControl/Management/FBSimulatorTerminationStrategy.h
FBSimulatorControl/Management/FBSimulatorTerminationStrategy.m
FBSimulatorControl/Utility/FBProcessQuery.h
FBSimulatorControl/Utility/FBProcessQuery.m

Much less severe than using `kill`, add an option to select the termination strategy.

Add NSWorkspace-based termination strategy

---

FBSimulatorControl/Management/FBSimulatorPool.m

When we fail to allocate simulator it will be way easier to understand what when wrong if we got information about runtime and type we tried to allocate.

Added more information when failing to allocate simulator

---

FBSimulatorControl.xcodeproj/project.pbxproj
FBSimulatorControl/Session/FBSimDeviceWrapper.h
FBSimulatorControl/Session/FBSimDeviceWrapper.m
FBSimulatorControl/Session/FBSimulatorSessionInteraction.m

We've seen these methods hang on Xcode 7.1, so let's make them timeout instead.
Because the API doesn't actually error out when anything goes wrong, we run them from a background thread and shuttle the results back to the main thread.
I also tested locally with FBSimulatorControlApplicationLaunchTests.

Add timeout to launching and installing applications on SimDevice

---

FBSimulatorControl/Configuration/FBSimulatorControlConfiguration.h
FBSimulatorControl/Management/FBSimulatorControl.m
FBSimulatorControl/Management/FBSimulatorPool.h
FBSimulatorControl/Management/FBSimulatorPool.m
FBSimulatorControl/Management/FBSimulatorTerminationStrategy.h
FBSimulatorControl/Management/FBSimulatorTerminationStrategy.m
FBSimulatorControl/Utility/FBProcessQuery+Simulators.h
FBSimulatorControl/Utility/FBProcessQuery+Simulators.m
FBSimulatorControlTests/Utilities/FBSimulatorControlTestCase.m

Having versions of `com.apple.CoreSimulator.CoreSimulatorService` hanging around can lead to issues when switching versions of xcode locally (and not rebooting). Using `xcode-select` will not kill the service, so this startup option adds another (optional) precondition.

Add Killing of CoreSimulatorService

---

FBSimulatorControl/Management/FBSimulatorLaunchInfo.m
FBSimulatorControl/Management/FBSimulatorTerminationStrategy.m
FBSimulatorControl/Utility/FBProcessQuery+Simulators.h
FBSimulatorControl/Utility/FBProcessQuery+Simulators.m
FBSimulatorControl/Utility/FBProcessQuery.h
FBSimulatorControl/Utility/FBProcessQuery.m
FBSimulatorControlTests/Tests/FBSimulatorControlSimulatorLaunchTests.m

It's possible to get `launchdservicesd` into a funk by shutting down Simulators too fast. Killing 2 or more simulators at the same time requires some time between kill/termination. By altering the way that multiple simulators are killed, we can ensure that there is sufficient time between kills to not get the dock in a funk.

Avoid confusing launchservicesd with fast multi-app termination

---

FBSimulatorControl/Management/FBSimulatorInteraction+Agents.m
FBSimulatorControl/Management/FBSimulatorInteraction+Applications.m
FBSimulatorControl/Session/FBSimDeviceWrapper.h
FBSimulatorControl/Session/FBSimDeviceWrapper.m
FBSimulatorControl/Utility/NSRunLoop+SimulatorControlAdditions.h
FBSimulatorControl/Utility/NSRunLoop+SimulatorControlAdditions.m

This can be used to update Simulator state and confirm the app has actually launched. This may also help weed out processes that are short-lived and die too-soon.

Get Process Info on Process Launch

---

FBSimulatorControl/Management/FBSimulatorPool+Private.h
FBSimulatorControl/Management/FBSimulatorPool.h
FBSimulatorControl/Management/FBSimulatorPool.m
FBSimulatorControl/Management/FBSimulatorTerminationStrategy.h
FBSimulatorControl/Management/FBSimulatorTerminationStrategy.m
FBSimulatorControl/Tiling/FBSimulatorWindowHelpers.h
FBSimulatorControl/Tiling/FBSimulatorWindowHelpers.m
FBSimulatorControlTests/Tests/FBSimulatorPoolAllocationTests.m
FBSimulatorControlTests/Tests/FBSimulatorPoolTests.m
fbsimctl/Sources/Command.swift
fbsimctl/Sources/Runners.swift

We are creating `FBSimulator` instances every time that the `allSimulators` property of `FBSimulatorPool` is called. In reality these objects are references and not values, as we want the process information to be updated in-place. This solves two issues:
1) Process Launch Info is only calculated once per Simulator
2) Notifications for Process lifecycle can be uniqued based on a single simulator instance, this means that notifications for Simulator and Simulator Subprocess launch can come from the Simulator itself.

Share FBSimulator instances

---

FBSimulatorControl/Configuration/FBSimulatorControlStaticConfiguration.h
FBSimulatorControl/Configuration/FBSimulatorControlStaticConfiguration.m
FBSimulatorControl/Management/FBSimulator.m
FBSimulatorControl/Management/FBSimulatorInteraction.m
FBSimulatorControl/Utility/FBProcessQuery+Simulators.m

Marking FBSimulatorControl simulators with FBSIMULATORCONTROL_SIM_UDID env. It will make it easer to FBSimulatorControl with other simulator managers.

Marking FBSimulatorControl simulators

---

FBSimulatorControl.xcodeproj/project.pbxproj
FBSimulatorControl/Model/FBSimulatorApplication.m
FBSimulatorControl/Utility/FBBinaryParser.h
FBSimulatorControl/Utility/FBBinaryParser.m

I believe that the `FBTask` implementation is a bit wonky on Travis which suggests some raciness that needs further investigation. However this 1) Doesn't repro for me locally 2) Only appears a bunch on the arch fetching. The arch fetching can be [re-implemented without too much effort](http://lowlevelbits.org/parse-mach-o-files/) by reading the header directly.

Read Mach-O Header

---

FBSimulatorControl/Configuration/FBSimulatorControlConfiguration.h
FBSimulatorControl/Interactions/FBSimulatorInteraction+Convenience.h
FBSimulatorControl/Interactions/FBSimulatorInteraction+Convenience.m
FBSimulatorControl/Interactions/FBSimulatorInteraction.m
FBSimulatorControl/Management/FBSimulator+Helpers.h
FBSimulatorControl/Management/FBSimulator+Helpers.m
FBSimulatorControl/Management/FBSimulatorControl+Class.h
FBSimulatorControl/Management/FBSimulatorControl.m
FBSimulatorControl/Management/FBSimulatorPool+Private.h
FBSimulatorControl/Management/FBSimulatorPool.h
FBSimulatorControl/Management/FBSimulatorPool.m
FBSimulatorControl/Management/FBSimulatorTerminationStrategy.h
FBSimulatorControl/Management/FBSimulatorTerminationStrategy.m
FBSimulatorControlTests/Tests/FBSimulatorControlConfigurationTests.m
FBSimulatorControlTests/Tests/FBSimulatorLaunchTests.m
FBSimulatorControlTests/Tests/FBSimulatorPoolAllocationTests.m
FBSimulatorControlTests/Utilities/FBSimulatorControlTestCase.h
FBSimulatorControlTests/Utilities/FBSimulatorControlTestCase.m

When running the CLI over a bunch of commands repeatedly there are currently two big shortcomings:
1) Allocating Simulators will erase and delete much more than is expected. This is because management options for allocation were global. This has now been replaced with per-allocation options in the form of `FBSimulatorAllocationOptions`. This breaks up `FBSimulatorManagementOptions` which was becoming very bloated.
2) Allocating can be slightly racey if there are Simulators without processes, but that are not 'Shutdown'. Placing an additional precondition that all Simulators are in a known-good state helps out here.

Pool Precondition to Shutdown processless Simulators

---

FBSimulatorControl.xcodeproj/project.pbxproj
FBSimulatorControl.xcodeproj/xcshareddata/xcschemes/FBSimulatorControl.xcscheme
FBSimulatorControl/Configuration/FBProcessLaunchConfiguration.h
FBSimulatorControl/Configuration/FBProcessLaunchConfiguration.m
FBSimulatorControl/Configuration/FBSimulatorControlStaticConfiguration.h
FBSimulatorControl/Configuration/FBSimulatorControlStaticConfiguration.m
FBSimulatorControl/Events/FBSimulatorEventRelay.m
FBSimulatorControl/Events/FBSimulatorLoggingEventSink.h
FBSimulatorControl/Events/FBSimulatorLoggingEventSink.m
FBSimulatorControl/FBSimulatorControl.h
FBSimulatorControl/Logs/FBSimulatorLogs.h
FBSimulatorControl/Logs/FBSimulatorLogs.m
FBSimulatorControl/Management/FBSimulator+Private.h
FBSimulatorControl/Management/FBSimulator.m
FBSimulatorControl/Management/FBSimulatorControl+Class.h
FBSimulatorControl/Management/FBSimulatorControl.m
FBSimulatorControl/Management/FBSimulatorPool+Private.h
FBSimulatorControl/Management/FBSimulatorPool.h
FBSimulatorControl/Management/FBSimulatorPool.m
FBSimulatorControl/Model/FBSimulatorLaunchInfo.h
FBSimulatorControl/Model/FBSimulatorLaunchInfo.m
FBSimulatorControl/Notifiers/FBCoreSimulatorNotifier.h
FBSimulatorControl/Notifiers/FBCoreSimulatorNotifier.m
FBSimulatorControl/Processes/FBProcessInfo.h
FBSimulatorControl/Processes/FBProcessInfo.m
FBSimulatorControlTests/Tests/FBSimulatorControlHistoryTests.m
FBSimulatorControlTests/Tests/FBSimulatorHistoryGeneratorTests.m
FBSimulatorControlTests/Tests/FBSimulatorPoolTests.m
FBSimulatorControlTests/Utilities/CoreSimulatorDoubles.h

- Adds an environment variable that is used to enable debug logging for Events that get propagated to a Simulator's Event Sink. 
- Strips away some of the cruft in `FBSimulatorPool` and replace with all the `FBSimulatorControl` niceties on the `debugDescription`.
- Automatic Enabling of the `CoreSimulator` debug log at `~/Library/Logs/CoreSimulator/CoreSimulator.log` via the environment variable
- Threading a `FBSimulatorLogger` from `FBSimulatorControl` down to the construction of `FBSimulatorLoggingEventSink`. This will also be useful in future to log interactions, termination strategy & redirection for `fbsimctl`.
- Short and Debug descriptions for `FBProcessInfo`, `FBSimulatorLaunchInfo` & `FBProcessLaunchConfiguration`. By implementing `debugDescription` these classes can trivially …

Debug Logging via FBSIMULATORCONTROL_DEBUG_LOGGING

---

FBSimulatorControl.xcodeproj/project.pbxproj
FBSimulatorControl/FBSimulatorControl.h
FBSimulatorControl/Logs/FBSimulatorLogs.m
FBSimulatorControl/Model/FBSimulatorHistory+Queries.h
FBSimulatorControl/Model/FBSimulatorHistory+Queries.m
FBSimulatorControl/Model/FBSimulatorHistory.h
FBSimulatorControl/Model/FBSimulatorHistory.m
FBSimulatorControl/Utility/FBCollectionDescriptions.h
FBSimulatorControl/Utility/FBCollectionDescriptions.m
FBSimulatorControlTests/Tests/FBSimulatorHistoryGeneratorTests.m
FBSimulatorControlTests/Tests/FBSimulatorLaunchTests.m

Sometimes you may want to query Simulator history in order to find out the last time a particular event occurred. In the case of logs you may want to know last time a Simulator was booted in order to narrow down information and discard pre-last-boot information. By adding queries by last-change-to-state it's possible to find this information.
In addition, the recursive description has been improved so that the ordering is correct and less-noisy descriptions are used.

Query History by State Change

---

FBSimulatorControl/Logs/FBASLParser.m
FBSimulatorControl/Logs/FBSimulatorLogs.m
FBSimulatorControl/Utility/FBConcurrentCollectionOperations.m
FBSimulatorControlTests/Tests/FBSimulatorLogsTests.m

Turns out that there's not any need to use a specific asl file since `asl` is just fine with a whole directory. It looks like different files are used at different times anyway and this could mean that certain messages go to different paths. Also made sure that all logs are forwarded with the debug log level.

Use directory of asl files

---

FBSimulatorControl.xcodeproj/project.pbxproj
build.sh
fbsimctl/fbsimctl.xcodeproj/project.pbxproj
fbsimctl/fbsimctl.xcodeproj/xcshareddata/xcschemes/fbsimctl.xcscheme

Now that we have Xcode 7.1 magically working on Travis, we can build `fbsimctl` there to make sure that we're not breaking `fbsimctl` changes with Framework changes.

Build fbsimctl on Travis

---

FBSimulatorControl/Configuration/FBSimulatorControlStaticConfiguration.h
FBSimulatorControl/Configuration/FBSimulatorControlStaticConfiguration.m
FBSimulatorControl/Management/FBSimulatorControl+Class.h
FBSimulatorControl/Management/FBSimulatorControl.m
FBSimulatorControlTests/Utilities/FBSimulatorControlTestCase.m

It's possible that the constructors are re-entrant and this causes issues with `otest-query-osx` used in `xctool`. It's better to place the onus of class loading on the consumer and additionally make it a precondition of `FBSimulatorContol`.
Additionally this removes the `+[DVTPlatform loadAllPlatformsReturningError:]` call. This call was actually *failing* but was being masked by the fact that the precondition method was erroneously never evaluated.

Opt-In for autoload of FBSimulatorControl Private Frameworks.

---

FBSimulatorControl/Configuration/FBSimulatorConfiguration.m
FBSimulatorControl/Configuration/FBSimulatorControlConfiguration.m
FBSimulatorControl/Configuration/FBSimulatorControlStaticConfiguration.h
FBSimulatorControl/Configuration/FBSimulatorControlStaticConfiguration.m
FBSimulatorControl/Management/FBSimulatorControl.m
FBSimulatorControl/Management/FBSimulatorPool.m
FBSimulatorControlTests/Utilities/FBSimulatorControlTestCase.m
README.md

This is probably the best balance between convenience and not having unexpected behaviour when `FBSimulatorControl` is first linked by clients.

Use +[NSObject initialize] when using CoreSimulator-dependent classes

---

FBSimulatorControl/Management/FBSimulator+Helpers.m
fbsimctl/FBSimulatorControlKit/Sources/Command.swift
fbsimctl/FBSimulatorControlKit/Sources/CommandParsers.swift
fbsimctl/FBSimulatorControlKitTests/Helpers/TestHelpers.swift
fbsimctl/FBSimulatorControlKitTests/Tests/CommandParsersTest.swift

Adds test for the parsing of `Format` enumerations, as well as fixes some of the parse issues that they have. Adds equality to `Format` and `Query` so that that parse successes are matched against the expected parse result.

Tests for Format Combinations

---

FBSimulatorControl/Configuration/FBSimulatorControlStaticConfiguration.h
FBSimulatorControl/Configuration/FBSimulatorControlStaticConfiguration.m
FBSimulatorControl/Interactions/FBSimulatorInteraction+Diagnostics.m
FBSimulatorControl/Management/FBSimulator+Helpers.m
FBSimulatorControl/Management/FBSimulator.h
FBSimulatorControl/Management/FBSimulator.m
FBSimulatorControl/Management/FBSimulatorPool.m
FBSimulatorControl/Tasks/FBTask.h
FBSimulatorControl/Tasks/FBTask.m
FBSimulatorControl/Tasks/FBTaskExecutor+Convenience.m
FBSimulatorControl/Utility/FBAddVideoPolyfill.m
FBSimulatorControl/Utility/FBSimDeviceWrapper.m

Using multiple values all over the place for timeouts means that it can be very tricky to find out if these thresholds are too low when it comes to a resource constrained CI system (Travis). At some point in the future it should be possible to override defaults, which may be important for the CLI use case.

Use 3-level timeouts

---

.travis.yml
build.sh

Travis has a ['Build Matrix'](https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix) that can be used to speed up builds by parallelizing. Some small modifications to the build scripts gives us the ability to paralellize

Use Travis build matrix to speed up CI

---

fbsimctl/FBSimulatorControlKit/Sources/CommandParsers.swift
fbsimctl/FBSimulatorControlKit/Sources/Parser.swift
fbsimctl/FBSimulatorControlKitTests/Tests/CommandParsersTest.swift

Some more tests for parsers, this time for option sets. This now places the responsibility for defaulting on empty parse to the caller of the parser.

Tests for Option-Set style parsers

---

fbsimctl/FBSimulatorControlKit/Sources/Arguments.swift
fbsimctl/FBSimulatorControlKit/Sources/Command.swift
fbsimctl/FBSimulatorControlKit/Sources/CommandParsers.swift
fbsimctl/FBSimulatorControlKit/Sources/Defaults.swift
fbsimctl/FBSimulatorControlKit/Sources/Parser.swift
fbsimctl/FBSimulatorControlKit/Sources/Runners.swift
fbsimctl/FBSimulatorControlKitTests/Helpers/TestHelpers.swift
fbsimctl/FBSimulatorControlKitTests/Tests/CommandParsersTest.swift
fbsimctl/fbsimctl.xcodeproj/project.pbxproj

Parsing of Actions

---

FBSimulatorControl/Events/FBSimulatorLoggingEventSink.m
FBSimulatorControl/Interactions/FBSimulatorInteraction.m
FBSimulatorControl/Management/FBSimulator.h
FBSimulatorControl/Management/FBSimulator.m
FBSimulatorControl/Management/FBSimulatorControl.m
FBSimulatorControl/Management/FBSimulatorPool.m
FBSimulatorControl/Management/FBSimulatorTerminationStrategy.h
FBSimulatorControl/Management/FBSimulatorTerminationStrategy.m
FBSimulatorControl/Utility/FBSimulatorError.h
FBSimulatorControl/Utility/FBSimulatorError.m
FBSimulatorControl/Utility/FBSimulatorLogger.h
FBSimulatorControl/Utility/FBSimulatorLogger.m
FBSimulatorControl/Video/FBSimulatorVideoRecorder.m

Adding log levels will allow for finer grained logging in the CLI use-case. Additionally, the addition of some logs will make it far easier to track down what the causes of failures are during a run of `FBSimulatorControl`.

Add Log Levels with additional error & debug logging

---

FBSimulatorControl/Configuration/FBSimulatorControlConfiguration.h
FBSimulatorControl/Configuration/FBSimulatorControlConfiguration.m
FBSimulatorControl/Interactions/FBSimulatorInteraction.m
FBSimulatorControl/Management/FBSimulator.h
FBSimulatorControl/Management/FBSimulator.m
FBSimulatorControl/Model/FBSimulatorApplication.h
FBSimulatorControl/Model/FBSimulatorApplication.m
FBSimulatorControl/Processes/FBProcessQuery+Simulators.m
FBSimulatorControlTests/Tests/FBSimulatorControlConfigurationTests.m
FBSimulatorControlTests/Tests/FBSimulatorPoolTests.m
FBSimulatorControlTests/Utilities/FBSimulatorControlTestCase.m
README.md
fbsimctl/FBSimulatorControlKit/Sources/CommandParsers.swift
fbsimctl/FBSimulatorControlKit/Sources/Defaults.swift
fbsimctl/FBSimulatorControlKitTests/Tests/CommandParsersTest.swift

This is effectively a Global requirement since it is derived from the `xcode-select` path. For this reason it makes more sense to be a global and not bloat the Configuration object.

Remove Simulator Application from FBSimulatorControlConfiguration

---

FBSimulatorControl/Configuration/FBSimulatorControlConfiguration.h
FBSimulatorControl/Configuration/FBSimulatorControlConfiguration.m
FBSimulatorControl/Configuration/FBSimulatorControlStaticConfiguration.m
FBSimulatorControl/Interactions/FBSimulatorInteraction.m
FBSimulatorControl/Management/FBSimulator.h
FBSimulatorControl/Management/FBSimulator.m
FBSimulatorControl/Model/FBSimulatorApplication.h
FBSimulatorControl/Model/FBSimulatorApplication.m
FBSimulatorControl/Processes/FBProcessQuery+Simulators.m
FBSimulatorControl/Utility/FBSimulatorLogger.h
FBSimulatorControl/Utility/FBSimulatorLogger.m
FBSimulatorControlTests/Tests/FBSimulatorControlConfigurationTests.m
FBSimulatorControlTests/Tests/FBSimulatorPoolTests.m
FBSimulatorControlTests/Utilities/FBSimulatorControlTestCase.m
README.md
fbsimctl/FBSimulatorControlKit/Sources/CommandParsers.swift
fbsimctl/FBSimulatorControlKit/Sources/Defaults.swift
fbsimctl/FBSimulatorControlKitTests/Tests/CommandParsersTest.swift

Passing the Debug logging flags after the creation of the global logger object is inconvenient since it makes controlling this at runtime impossible without making assumptions about initialization order in the CLI. `asl` makes it easy to pipe to additional files.

Add Debug Logging after creation

---

FBSimulatorControl.xcodeproj/project.pbxproj
FBSimulatorControl/Configuration/FBSimulatorConfiguration.h
FBSimulatorControl/Configuration/FBSimulatorConfiguration.m
FBSimulatorControl/FBSimulatorControl.h
FBSimulatorControl/Interactions/FBInteraction+Private.h
FBSimulatorControl/Interactions/FBInteraction.h
FBSimulatorControl/Interactions/FBSimulatorInteraction+Agents.m
FBSimulatorControl/Interactions/FBSimulatorInteraction+Applications.h
FBSimulatorControl/Interactions/FBSimulatorInteraction+Applications.m
FBSimulatorControl/Interactions/FBSimulatorInteraction+Diagnostics.m
FBSimulatorControl/Interactions/FBSimulatorInteraction+Lifecycle.h
FBSimulatorControl/Interactions/FBSimulatorInteraction+Lifecycle.m
FBSimulatorControl/Interactions/FBSimulatorInteraction+Private.h
FBSimulatorControl/Interactions/FBSimulatorInteraction+Setup.h
FBSimulatorControl/Interactions/FBSimulatorInteraction+Setup.m
FBSimulatorControl/Interactions/FBSimulatorInteraction+Upload.h
FBSimulatorControl/Interactions/FBSimulatorInteraction+Upload.m
FBSimulatorControl/Interactions/FBSimulatorInteraction+Video.h
FBSimulatorControl/Interactions/FBSimulatorInteraction+Video.m
FBSimulatorControl/Interactions/FBSimulatorInteraction.h
FBSimulatorControl/Interactions/FBSimulatorInteraction.m
FBSimulatorControl/Management/FBSimulatorPool.m
FBSimulatorControl/Management/FBSimulatorTerminationStrategy.m
FBSimulatorControlTests/Utilities/FBSimulatorControlTestCase.m

Most Interactions do not confirm that the Simulator is in a Booted/Shutdown state before proceeding, this can result in multiple of the same simulator being erroneously booted if the caller of the API doesn't check the state first. This is especially important for the cli use-case.

Preconditions for Simulator Interactions

---

fbsimctl/FBSimulatorControlKit/Sources/CommandParsers.swift
fbsimctl/FBSimulatorControlKit/Sources/Parser.swift
fbsimctl/FBSimulatorControlKit/Sources/Relay.swift
fbsimctl/FBSimulatorControlKit/Sources/Runners.swift
fbsimctl/FBSimulatorControlKit/Sources/SocketRelay.swift
fbsimctl/FBSimulatorControlKit/Sources/StdIORelay.swift
fbsimctl/FBSimulatorControlKit/Sources/Writer.swift
fbsimctl/fbsimctl.xcodeproj/project.pbxproj

Since a `Query` can result in multiple Simulators being matched it's important to be able to output success messages incrementally (for example in Booting). It's also important to be able to distinguish between 'logger' messages and 'output' messages; logger messages are informational and fine grained, output messages represent the result of an API call which would closely map to the return value of API calls.

Continuous console output for runners

---

FBSimulatorControl/Interactions/FBSimulatorInteraction+Applications.m
FBSimulatorControl/Management/FBSimulator+Helpers.h
FBSimulatorControl/Management/FBSimulator+Helpers.m

Providing a higher-level query for finding installed apps by bundle ID will help for the case where an Application launched and it's not known whether the Application needs to be installed or not.

Convenience for Fetching Installed App by Bundle ID

---

FBSimulatorControl/Model/FBSimulatorHistory+Queries.h
FBSimulatorControl/Model/FBSimulatorHistory+Queries.m
FBSimulatorControlTests/Tests/FBSimulatorLaunchTests.m

It can be helpful to access launch configurations for launches that may be more than n-1 (and therefore re-launchable with `relaunchApp`)

Add All Process/Agent/User launch configuration query

---

FBSimulatorControl/Events/FBSimulatorEventRelay.m
FBSimulatorControl/Model/FBSimulatorLaunchInfo.h
FBSimulatorControl/Model/FBSimulatorLaunchInfo.m

It's good to have the state update for simulators that are not launched directly via FBSimulatorControl, but FBSimulatorControl is used as a helper to manage them and for some helpful APIs.

Added wait with timeout when looking for launchInfo of FBSimulatorControled simulator

---

FBSimulatorControl/Model/FBSimulatorHistory+Queries.h
FBSimulatorControl/Model/FBSimulatorHistory+Queries.m
FBSimulatorControlTests/Fixtures/FBSimulatorControlFixtures.h
FBSimulatorControlTests/Fixtures/FBSimulatorControlFixtures.m
FBSimulatorControlTests/Tests/FBSimulatorHistoryGeneratorTests.m

The `allProcessLaunches` value previously relied on the ordering of the `allValues` array in a dictionary, which has arbitrary ordering. Instead the array of `allProcessLaunches` can be constructed from the ordered `processLaunchConfigurations` collection.

Non-Arbitrary Ordering for Process Launch Configs in History

---

fbsimctl/FBSimulatorControlKit/Sources/Command.swift
fbsimctl/FBSimulatorControlKit/Sources/CommandParsers.swift
fbsimctl/FBSimulatorControlKit/Sources/Runners.swift
fbsimctl/FBSimulatorControlKitTests/Tests/CommandParsersTest.swift

`Action` has moved to a struct with members `Query`, `Format` & `Interaction`. This fulfills a few needs:
- There is far less duplication of performing queries on an `Action` since all actions have a query.
- The output format of all actions uses the `Format`
- Future `Interaction` cases that don't rely on any associated types are simpler to implement
- `Interaction` cases map closer to `FBSimulatorInteraction`.
- `Help` should be easier to define.

Move Query & Format to Top Level of an Action

---

FBSimulatorControl/Events/FBSimulatorHistoryGenerator.h
FBSimulatorControl/Events/FBSimulatorHistoryGenerator.m
FBSimulatorControl/Management/FBSimulator+Private.h
FBSimulatorControl/Management/FBSimulator.m
FBSimulatorControl/Management/FBSimulatorPool.h
FBSimulatorControl/Management/FBSimulatorPool.m
FBSimulatorControlTests/Tests/FBSimulatorControlHistoryTests.m
FBSimulatorControlTests/Tests/FBSimulatorHistoryGeneratorTests.m
FBSimulatorControlTests/Utilities/CoreSimulatorDoubles.h
FBSimulatorControlTests/Utilities/CoreSimulatorDoubles.m

This can be used to re-inflate the knowledge of the history of a Simulator when a Simulator is created. Very handy for the CLI use case, which can work via multiple invocations of a process linking `FBSimulatorControl`.

Optionally persist Simulator history to file

---

FBSimulatorControl/Interactions/FBSimulatorInteraction+Lifecycle.m
FBSimulatorControl/Model/FBSimulatorApplication.h
FBSimulatorControl/Model/FBSimulatorApplication.m
FBSimulatorControl/Processes/FBProcessQuery+Simulators.m
fbsimctl/FBSimulatorControlKit/Sources/Command.swift
fbsimctl/FBSimulatorControlKit/Sources/CommandParsers.swift
fbsimctl/FBSimulatorControlKit/Sources/Parser.swift
fbsimctl/FBSimulatorControlKit/Sources/Runners.swift
fbsimctl/FBSimulatorControlKitTests/Tests/CommandParsersTest.swift

Adds `install` to the cli actions. Utilizes the validation in `FBSimulatorApplication` constructors to parse the App path. Had to change the poorly-named `+[FBSimulatorApplication simulatorApplication]` as it (understandably) confuses the Objective-C to Swift module export.

Install Action

---

FBSimulatorControl.xcodeproj/project.pbxproj
FBSimulatorControl/FBSimulatorControl.h
FBSimulatorControl/Management/FBCoreSimulatorTerminationStrategy.h
FBSimulatorControl/Management/FBCoreSimulatorTerminationStrategy.m
FBSimulatorControl/Management/FBProcessTerminationStrategy.h
FBSimulatorControl/Management/FBProcessTerminationStrategy.m
FBSimulatorControl/Management/FBSimulatorPool.h
FBSimulatorControl/Management/FBSimulatorPool.m
FBSimulatorControl/Management/FBSimulatorTerminationStrategy.h
FBSimulatorControl/Management/FBSimulatorTerminationStrategy.m
FBSimulatorControl/Utility/FBSimDeviceWrapper.h
FBSimulatorControl/Utility/FBSimDeviceWrapper.m

Given that it will soon be possible to boot Simulators (and get a framebuffer #150) without a `Simulator.app` process, it's important that  `FBSimulatorTerminationStrategy` can account for this. 
This change improves things in this regard:
1) Makes `FBSimulatorTerminationStrategy` a bit simpler and easier to comprehend
2) Documentation
3) Doesn't couple Application Termination to the `Simulator.app`, processes that are applications can get use `NSWorkspace` termination for free.
4) Fallback behaviour for `NSWorkspace` termination.
5) Separating the concerns of 'killing the Simulator.app' process vs. 'shutting down a Simulator'. This will be important in #150 as getting `CoreSimulator` into a stable state on launch may not require killing `Simulator.app` processes.

Killing Simulators accounts for Simulator.app-less booted Simulators.

---

fbsimctl/FBSimulatorControlKit/Sources/Command.swift
fbsimctl/FBSimulatorControlKit/Sources/CommandParsers.swift
fbsimctl/FBSimulatorControlKit/Sources/Runners.swift
fbsimctl/FBSimulatorControlKitTests/Helpers/Fixtures.swift
fbsimctl/FBSimulatorControlKitTests/Tests/CommandParsersTests.swift

Adds a 'Launch' Action for launching agents and applications. Current implementation won't take arguments but I plan on fixing this by changing the ordering of the grammar so the `Interaction` is parsed after the `Query` thereby making variadic arguments apply to the `Interaction`.

'launch' Action

---

fbsimctl/FBSimulatorControlKit/Sources/Environment.swift
fbsimctl/FBSimulatorControlKit/Sources/Parser.swift
fbsimctl/FBSimulatorControlKitTests/Tests/EnvironmentTests.swift
fbsimctl/fbsimctl.xcodeproj/project.pbxproj
fbsimctl/fbsimctl/main.swift

Apes `simctl` with it's `SIMCTL_CHILD`. Instead we use `FBSIMCTL_CHILD`

Update Launch Configs with Environment Variables

---

FBSimulatorControl/Events/FBSimulatorHistoryGenerator.m
FBSimulatorControl/Model/FBSimulatorHistory+Queries.h
FBSimulatorControl/Model/FBSimulatorHistory+Queries.m
FBSimulatorControl/Model/FBSimulatorHistory.h
FBSimulatorControl/Model/FBSimulatorHistory.m

Being able to interrogate the history of process termination without the need for notification callbacks can be pretty handy, so `FBSimulatorHistoryGenerator` now records this in the diagnostics dictionary.

Add Termination status to Process Diagnostics

---

fbsimctl/FBSimulatorControlKit/Sources/CommandParsers.swift
fbsimctl/FBSimulatorControlKitTests/Tests/CommandParsersTests.swift

In order to make parsing context-free and to remove any ambiguity about what `shutdown` means, I'm changing `shutdown` the query to `--state=shutdown` so that it isn't confused with `shutdown` the interaction.

Use --state= prefix for state queries

---

fbsimctl/FBSimulatorControlKit/Sources/Runners.swift
fbsimctl/fbsimctl/main.swift

Failing commands should result in a return code.

Use exit(3) for a return code on success or failure

---

fbsimctl/FBSimulatorControlKit/Sources/CommandParsers.swift
fbsimctl/FBSimulatorControlKitTests/Tests/CommandParsersTests.swift

Changes the grammar from:
`[interaction] [query] [format]`
To:
`[query] [format] [interaction]`
There's a very good reason for doing this; the `Interaction` can have associated values, and these values may be variadic. This will be important for the `launch` interaction, which should in future be able to take arguments to the launched process after the `launch` command. 
If the `Interact` part was expected to be first in the `Action` then the arguments to the launched process would have to be escaped.

Move Interaction to the end of the Action

---

FBSimulatorControl/Utility/FBSimDeviceWrapper.m

In the `TimeoutResiliance` case for `FBSimDeviceWrapper` we don't do anything with the error from `SimDevice` so the underlying error cause can get missed, this is problematic on Xcode 7.2 which still seems to have issues with `installApplication:`

Extract underlying error when executing FBSimDeviceWrapper methods

---

FBSimulatorControl.xcodeproj/project.pbxproj
FBSimulatorControl/Configuration/FBSimulatorLaunchConfiguration+Private.h
FBSimulatorControl/Configuration/FBSimulatorLaunchConfiguration.m
FBSimulatorControl/FBSimulatorControl.h
fbsimctl/FBSimulatorControlKit/Sources/Command.swift
fbsimctl/FBSimulatorControlKit/Sources/CommandParsers.swift
fbsimctl/FBSimulatorControlKit/Sources/Runners.swift
fbsimctl/FBSimulatorControlKitTests/Tests/CommandParsersTests.swift

This allows for the locale to be set before booting as well as the scale for the boot itself. This will also be able to account for options in the future when I finally get round to finishing #150

Use FBSimulatorLaunchConfiguration to configure simulator before boot

---

FBSimulatorControl.xcodeproj/project.pbxproj
FBSimulatorControl/Configuration/FBProcessLaunchConfiguration+Helpers.h
FBSimulatorControl/Configuration/FBProcessLaunchConfiguration+Helpers.m
FBSimulatorControl/FBSimulatorControl.h
FBSimulatorControl/Interactions/FBSimulatorInteraction+Agents.m
FBSimulatorControl/Interactions/FBSimulatorInteraction+Applications.m
FBSimulatorControl/Management/FBSimulator+Helpers.h
FBSimulatorControl/Management/FBSimulator+Helpers.m
FBSimulatorControl/Model/FBSimulatorApplication.h
FBSimulatorControl/Model/FBSimulatorApplication.m
FBSimulatorControl/Utility/FBSimDeviceWrapper.h
FBSimulatorControl/Utility/FBSimDeviceWrapper.m
FBSimulatorControl/Utility/FBSimulatorLaunchCtl.h
FBSimulatorControl/Utility/FBSimulatorLaunchCtl.m
FBSimulatorControlTests/Tests/FBSimulatorLaunchTests.m
FBSimulatorControlTests/Utilities/FBSimulatorControlAssertions.h
FBSimulatorControlTests/Utilities/FBSimulatorControlAssertions.m

In #175 I discovered a race that can occur between the killing of a process and the Simulator's knowledge of this process in `launchctl`.
By looking at `launchctl`s knowledge of the world by spawning a `launchctl` process from `FBSimulatorControl` (via `CoreSimulator`) we can know whether `launchctl` is aware of the process or not. I am looking to add features to this class over time as there's plenty of useful information in `launchctl` that we currently don't have access to in `FBSimulatorControl`.

Add Wrapper to Simulator's launchctl

---

FBSimulatorControl/Management/FBSimulator+Helpers.h
FBSimulatorControl/Management/FBSimulator+Helpers.m

This pull request is to add a method for FBSimulatorControl to return the home directory for the last app launched.

Add method to return home directory for last app launched

---

FBSimulatorControl/Configuration/FBProcessLaunchConfiguration+Private.h
FBSimulatorControl/Configuration/FBProcessLaunchConfiguration.h
FBSimulatorControl/Configuration/FBProcessLaunchConfiguration.m
FBSimulatorControl/Interactions/FBSimulatorInteraction+Applications.h
FBSimulatorControl/Interactions/FBSimulatorInteraction+Applications.m
FBSimulatorControl/Interactions/FBSimulatorInteraction+Lifecycle.h
FBSimulatorControl/Interactions/FBSimulatorInteraction+Lifecycle.m
FBSimulatorControl/Interactions/FBSimulatorInteraction+Private.h
FBSimulatorControl/Interactions/FBSimulatorInteraction.m
FBSimulatorControl/Management/FBCoreSimulatorTerminationStrategy.m
FBSimulatorControl/Management/FBProcessTerminationStrategy.h
FBSimulatorControl/Management/FBProcessTerminationStrategy.m
FBSimulatorControl/Management/FBSimulatorTerminationStrategy.m
FBSimulatorControl/Model/FBSimulatorApplication.m
FBSimulatorControl/Model/FBSimulatorHistory+Queries.m
FBSimulatorControl/Utility/FBAddVideoPolyfill.m
FBSimulatorControl/Utility/FBBinaryParser.m
FBSimulatorControlTests/Fixtures/FBSimulatorControlFixtures.m
FBSimulatorControlTests/Tests/FBProcessLaunchConfigurationTests.m
FBSimulatorControlTests/Tests/FBSimulatorAutomaticUpdatingTests.m
FBSimulatorControlTests/Tests/FBSimulatorControlHistoryTests.m
FBSimulatorControlTests/Tests/FBSimulatorHistoryGeneratorTests.m
FBSimulatorControlTests/Tests/FBSimulatorLaunchTests.m
FBSimulatorControlTests/Tests/FBSimulatorLogsTests.m
fbsimctl/FBSimulatorControlKit/Sources/CommandParsers.swift
fbsimctl/FBSimulatorControlKitTests/Tests/CommandParsersTests.swift

It should be possible to launch an Application without the location of the source Application. The path to the original binary makes less sense considering the Application is installed relative to the `data` directory of Simulator, so the original location of the `Application` binary isn't used when the Application is a launched on the Simulator.

FBApplicationLaunchConfiguration defined in terms of Bundle ID

---

FBSimulatorControl/Interactions/FBSimulatorInteraction+Applications.h
FBSimulatorControl/Interactions/FBSimulatorInteraction+Applications.m
FBSimulatorControl/Interactions/FBSimulatorInteraction+Lifecycle.h
FBSimulatorControl/Interactions/FBSimulatorInteraction+Lifecycle.m
FBSimulatorControl/Interactions/FBSimulatorInteraction+Private.h
FBSimulatorControl/Interactions/FBSimulatorInteraction.m
FBSimulatorControl/Management/FBCoreSimulatorTerminationStrategy.m
FBSimulatorControl/Management/FBProcessTerminationStrategy.h
FBSimulatorControl/Management/FBProcessTerminationStrategy.m
FBSimulatorControl/Management/FBSimulatorTerminationStrategy.m
FBSimulatorControl/Utility/FBAddVideoPolyfill.m
FBSimulatorControlTests/Tests/FBSimulatorAutomaticUpdatingTests.m
FBSimulatorControlTests/Tests/FBSimulatorLaunchTests.m

Instead of just having `killApplication:` to kill applications, we should expose an API to do this for any subprocess of the simulator. We can add additional checks so that we don't kill random processes on a host and also use the existing `FBSimulatorTerminationStrategy`
Additionally, it looks like there is a race condition in the relaunch case:
1) An app is launched and has a pid
2) The app is terminated
3) Wait for the pid to disappear
4) Relaunch the app with the same launch configuration
5) The relaunched app will have the same pid as 1)
6) We try and fetch the process info for the pid, but it has died.
I can only assume that `CoreSimulator` will talk to the `launchd_sim` inside the Simulator and as the process was killed externally, it has to update it's knowledge of the world to …

Improve launchd_sim subprocess killing

---

FBSimulatorControl/Configuration/FBProcessLaunchConfiguration+Private.h
FBSimulatorControl/Configuration/FBProcessLaunchConfiguration.h
FBSimulatorControl/Configuration/FBProcessLaunchConfiguration.m
fbsimctl/FBSimulatorControlKit/Sources/CommandParsers.swift
fbsimctl/FBSimulatorControlKitTests/Tests/CommandParsersTests.swift

This is an (optional) but nonetheless useful piece of information. Also clarifies the nullability semantics.

Add Bundle Name to FBApplicationLaunchConfiguration

---

FBSimulatorControl.xcodeproj/project.pbxproj
FBSimulatorControl/Configuration/FBProcessLaunchConfiguration.h
FBSimulatorControl/Configuration/FBProcessLaunchConfiguration.m
FBSimulatorControl/FBSimulatorControl.h
FBSimulatorControl/Logs/FBWritableLog.h
FBSimulatorControl/Logs/FBWritableLog.m
FBSimulatorControl/Management/FBSimulator.h
FBSimulatorControl/Management/FBSimulator.m
FBSimulatorControl/Model/FBJSONSerializationDescribeable.h
FBSimulatorControl/Model/FBSimulatorApplication.h
FBSimulatorControl/Model/FBSimulatorApplication.m
FBSimulatorControl/Processes/FBProcessInfo.h
FBSimulatorControl/Processes/FBProcessInfo.m
fbsimctl/FBSimulatorControlKit/Sources/JSON.swift
fbsimctl/FBSimulatorControlKit/Sources/Runners.swift

Adds a protocol for defining `NSObject`s that can be represented in a `NSDictionary` that is serializable with `NSJSONSerialization`

Add FBJSONSerializationDescribeable Protocol

---

FBSimulatorControl.xcodeproj/project.pbxproj
FBSimulatorControl/Configuration/FBProcessLaunchConfiguration.h
FBSimulatorControl/Configuration/FBProcessLaunchConfiguration.m
FBSimulatorControl/Configuration/FBSimulatorLaunchConfiguration.h
FBSimulatorControl/Configuration/FBSimulatorLaunchConfiguration.m
FBSimulatorControl/FBSimulatorControl.h
FBSimulatorControl/Logs/FBWritableLog.h
FBSimulatorControl/Logs/FBWritableLog.m
FBSimulatorControl/Management/FBSimulator.h
FBSimulatorControl/Management/FBSimulator.m
FBSimulatorControl/Management/FBSimulatorPool.h
FBSimulatorControl/Management/FBSimulatorPool.m
FBSimulatorControl/Model/FBDebugDescribeable.h
FBSimulatorControl/Model/FBJSONSerializationDescribeable.h
FBSimulatorControl/Model/FBSimulatorApplication.h
FBSimulatorControl/Model/FBSimulatorApplication.m
FBSimulatorControl/Processes/FBProcessInfo.h
FBSimulatorControl/Processes/FBProcessInfo.m
fbsimctl/FBSimulatorControlKit/Sources/JSON.swift
fbsimctl/FBSimulatorControlKit/Sources/Runners.swift

`debugDescription` was previously defined per-class. This makes conformance to `CustomDebugStringConvertible` trivial for classes that conform as they already have the appropriate methods

Add FBDebugDescribeable Protocol

---

FBSimulatorControl/Interactions/FBSimulatorInteraction+Diagnostics.m
FBSimulatorControl/Interactions/FBSimulatorInteraction+Video.m
FBSimulatorControl/Logs/FBSimulatorLogs.h
FBSimulatorControl/Logs/FBSimulatorLogs.m
FBSimulatorControl/Logs/FBWritableLog.h
FBSimulatorControl/Logs/FBWritableLog.m

It made little sense to have a `logBuilder` property, so that all logs could be configured with the Simulator's auxillary directory. Instead all logs are derived from a 'base' log that can be built on top of. This means that video recording can build on top of the video property of `FBSimulatorLogs`.

Remove logBuilder property

---

FBSimulatorControl/Configuration/FBSimulatorLaunchConfiguration.h
FBSimulatorControl/Interactions/FBSimulatorInteraction+Lifecycle.m

`NSWorkspace` provides a very nice API for launching Applications, and will even fit our requirements of:
- Providing launch arguments
- Providing launch environment
- Always launching a new Application instance, even if one or more is already running.
Weaning ourselves of `FBTask` is a good idea in general since It's another thing to go wrong™️. We'll get better error messaging from the `NSWorkspace` API. Additionally, the work for `fbsimctl` to ensure that the `Simulator.app` process lifetime is not dictated by the lifetime of the containing `FBSimulatorControl` process means that `FBSimulatorTerminationStrategy` is the most suitable place for knowledge for how to terminate an application, rather than a subprocess.

Use NSWorkspace API for Launching Simulator Applications

---

FBSimulatorControl/Framebuffer/FBSimulatorFramebuffer.h
FBSimulatorControl/Framebuffer/FBSimulatorFramebuffer.m
FBSimulatorControl/Interactions/FBSimulatorInteraction+Lifecycle.m

This is another missing piece of the Framebuffer implementation, meaning that the implementation is similar to the startup path that `Simulator.app` takes.
Before this change, it was possible that `[UIATarget tap]` (used by WebDriverAgent) would not work when a Simulator is booted in this manner. The actual event dispatch to the HID Subsystem occurs at `IOHIDEventSystemClientDispatchEvent`, and will fail without a 'Indigo HID system' registered with `backboardd`.

Create and Register a 'IndigoHIDRegistrationPort' Port

---

FBSimulatorControl/Configuration/FBSimulatorControlConfiguration.h
FBSimulatorControl/Interactions/FBSimulatorInteraction+Applications.m
FBSimulatorControl/Interactions/FBSimulatorInteraction+Lifecycle.m
FBSimulatorControl/Management/FBCoreSimulatorTerminationStrategy.m
FBSimulatorControl/Management/FBProcessTerminationStrategy.h
FBSimulatorControl/Management/FBProcessTerminationStrategy.m
FBSimulatorControl/Management/FBSimulatorTerminationStrategy.m
FBSimulatorControl/Processes/FBProcessQuery+Helpers.h
FBSimulatorControl/Processes/FBProcessQuery+Helpers.m
fbsimctl/FBSimulatorControlKit/Sources/CommandParsers.swift
fbsimctl/FBSimulatorControlKitTests/Tests/CommandParsersTests.swift

`FBProcessTerminationStrategy` has a bunch of behaviours on top of `kill` making these explicit with an option set means that behaviour is more understandable. `FBSimulatorManagementOptionsUseProcessKilling` no longer makes sense as it is always the fallback.
Additionally, the relaunch interaction could result in strange behaviour when the failure to kill an existing application was suppressed. As a result, the app wouldn't be re-launched at all.

Add Configuration to FBProcessTerminationStrategy

---

FBSimulatorControl/Framebuffer/FBFramebufferCompositeDelegate.m
FBSimulatorControl/Framebuffer/FBFramebufferDebugWindow.m
FBSimulatorControl/Framebuffer/FBFramebufferDelegate.h
FBSimulatorControl/Framebuffer/FBFramebufferImage.h
FBSimulatorControl/Framebuffer/FBFramebufferImage.m
FBSimulatorControl/Framebuffer/FBFramebufferVideo.h
FBSimulatorControl/Framebuffer/FBFramebufferVideo.m
FBSimulatorControl/Framebuffer/FBSimulatorFramebuffer.h
FBSimulatorControl/Framebuffer/FBSimulatorFramebuffer.m
FBSimulatorControl/Management/FBSimulatorBridge.h
FBSimulatorControl/Management/FBSimulatorBridge.m
FBSimulatorControl/Management/FBSimulatorTerminationStrategy.m

It can be frustrating when the teardown of the `FBSimualtorControl` process races with the the final writing of a video to disk, as this can lead to incomplete videos.
By using `dispatch_group`s for the semaphore-like semantics and `dispatch_wait` we can pass down a group to `FBSimulatorFramebufferDelegate`'s so that they perform some teardown work, asynchronous with the main thread.

Framebuffer Completion Wait

---

FBSimulatorControl/Framebuffer/FBFramebufferVideo.m

`movieFragmentInterval` is still being problematic, and we'd much rather use the more web-friendly `AVFileTypeMPEG4`. It looks like the `pixelBufferPool` of the `AVAssetWriterInputPixelBufferAdaptor` was going to nil during the run so we can add some error messaging for that also.

Video Recording Settings Improvements

---

FBSimulatorControl/Interactions/FBSimulatorInteraction+Applications.h
FBSimulatorControl/Interactions/FBSimulatorInteraction+Applications.m
fbsimctl/FBSimulatorControlKit/Sources/Command.swift
fbsimctl/FBSimulatorControlKit/Sources/CommandParsers.swift
fbsimctl/FBSimulatorControlKit/Sources/Runners.swift
fbsimctl/FBSimulatorControlKitTests/Tests/CommandParsersTests.swift

Adds an API to terminate an application by a specific bundle ID. I want to revisit this later to ensure that that we specify 'interacting' with a process via bundle ids, app paths and pids as this will make the API far more flexible.

Terminate Application

---

fbsimctl/FBSimulatorControlKit/Sources/Command.swift
fbsimctl/FBSimulatorControlKit/Sources/CommandParsers.swift
fbsimctl/FBSimulatorControlKit/Sources/EventReporter.swift
fbsimctl/FBSimulatorControlKit/Sources/Events.swift
fbsimctl/FBSimulatorControlKit/Sources/HttpRelay.swift
fbsimctl/FBSimulatorControlKit/Sources/JSON.swift
fbsimctl/FBSimulatorControlKit/Sources/Parser.swift
fbsimctl/FBSimulatorControlKit/Sources/Relay.swift
fbsimctl/FBSimulatorControlKit/Sources/Runners.swift
fbsimctl/FBSimulatorControlKit/Sources/SignalHandler.swift
fbsimctl/FBSimulatorControlKit/Sources/SocketRelay.swift
fbsimctl/FBSimulatorControlKit/Sources/StdIORelay.swift
fbsimctl/FBSimulatorControlKitTests/Tests/CommandParsersTests.swift

The Listen Commands need a little polish:

Improve Listen Lifecycle

---

FBSimulatorControl/Interactions/FBInteraction.m

#205 was the first master run [to exhibit duping of logs](https://travis-ci.org/facebook/FBSimulatorControl/jobs/108248085). This was verified in Instruments.

Fix Retain Cycle in FBInteraction

---

FBSimulatorControl/Interactions/FBSimulatorInteraction+Applications.m

This could be optional in future, or we should have an API for disabling background modes for applications.

Don't fail to launch if Application was launched in the background

---

fbsimctl/FBSimulatorControlKit/Sources/CommandParsers.swift
fbsimctl/FBSimulatorControlKit/Sources/Defaults.swift
fbsimctl/FBSimulatorControlKit/Sources/Query.swift
fbsimctl/FBSimulatorControlKit/Sources/Runners.swift
fbsimctl/FBSimulatorControlKitTests/Tests/CommandParsersTests.swift

There's currently no way of selecting 'all' simulators when performing a query, this means that killing or deleting all the simulators has to be done via pool preconditions like `--delete-all` and `--kill-all`. This doesn't make a huge amount of sense, as having purpose built operations is much more obvious. 
Also adds defaulting of `Query` for the `list` command so that `fbsimctl list` lists all Simulators.

Add 'all' as query for targeting all Simulators

---

fbsimctl/FBSimulatorControlKit/Sources/Command.swift
fbsimctl/FBSimulatorControlKit/Sources/CommandParsers.swift
fbsimctl/FBSimulatorControlKit/Sources/Defaults.swift
fbsimctl/FBSimulatorControlKit/Sources/Environment.swift
fbsimctl/FBSimulatorControlKit/Sources/HttpRelay.swift
fbsimctl/FBSimulatorControlKit/Sources/Parser.swift
fbsimctl/FBSimulatorControlKit/Sources/Query.swift
fbsimctl/FBSimulatorControlKit/Sources/Runners.swift
fbsimctl/FBSimulatorControlKitTests/Tests/CommandParsersTests.swift
fbsimctl/FBSimulatorControlKitTests/Tests/EnvironmentTests.swift

Removing the distinction between `Interaction` and `Action` is worthwhile as it will allow actions to compose far easier. With the presence of `Defaults` to pass through 'the last Simulator we called' chains with booting and listening become easy:
`fbsimct create 'iPhone 5' boot --direct-launch --record-video listen --http 8090 shutdown diagnose`
This will create then boot a simulator, recording the Framebuffer's video, then listen on port 8090. When a `SIGTERM` is sent to the process, it will shutdown and print out the logs.
This should also make it a bit easier to write help.

Chainable Actions

---

FBSimulatorControl/Configuration/FBProcessLaunchConfiguration+Helpers.m

This can confuse launched processes as the `argv[0]` isn't automatically set, it just uses the arguments array verbatim.

Fix argv[0] on agent launches to be the executable path

---

fbsimctl/FBSimulatorControlKit/FBSimulatorControlKit.h
fbsimctl/FBSimulatorControlKit/Sources/Bridging.h
fbsimctl/FBSimulatorControlKit/Sources/Bridging.m
fbsimctl/FBSimulatorControlKit/Sources/Events.swift
fbsimctl/fbsimctl.xcodeproj/project.pbxproj
fbsimctl/fbsimctl/JSONLogger.h
fbsimctl/fbsimctl/fbsimctl.h
fbsimctl/fbsimctl/main.swift

Looks like Swift doesn't like certain protocol extensions and will sporadically fail. This should fix that.

Workaround 'Duplicate Protocol Conformance' Errors

---

fbsimctl/FBSimulatorControlKit/Sources/CommandParsers.swift

Relative Paths (such as those with a tilde) won't be parsed which makes little sense. This fixes that.

Standardize Relative Paths

---

fbsimctl/FBSimulatorControlKit/Sources/Command.swift
fbsimctl/FBSimulatorControlKit/Sources/CommandParsers.swift
fbsimctl/FBSimulatorControlKit/Sources/CommandPerformer.swift
fbsimctl/FBSimulatorControlKit/Sources/Defaults.swift
fbsimctl/FBSimulatorControlKit/Sources/EventReporter.swift
fbsimctl/FBSimulatorControlKit/Sources/HttpRelay.swift
fbsimctl/FBSimulatorControlKit/Sources/Parser.swift
fbsimctl/FBSimulatorControlKit/Sources/Relay.swift
fbsimctl/FBSimulatorControlKit/Sources/Runners.swift
fbsimctl/FBSimulatorControlKit/Sources/SocketRelay.swift
fbsimctl/FBSimulatorControlKit/Sources/StdIORelay.swift
fbsimctl/FBSimulatorControlKitTests/Tests/CommandParsersTests.swift
fbsimctl/fbsimctl.xcodeproj/project.pbxproj
fbsimctl/fbsimctl/main.swift

Previous iterations of any `Listen` mode have fixed the `Query` to the `Query` of the `Listen` command. This is less desirable than allowing this to be optionally changed.

Build ActionPerformer from CommandPerformer

---

FBSimulatorControl/Interactions/FBInteraction.h
FBSimulatorControl/Interactions/FBInteraction.m
FBSimulatorControl/Interactions/FBSimulatorInteraction+Applications.m
FBSimulatorControl/Utility/FBAddVideoPolyfill.m
FBSimulatorControlTests/Utilities/FBSimulatorControlAssertions.m
README.md
fbsimctl/FBSimulatorControlKit/Sources/Runners.swift

Seems a bit silly to encode the reciever's protocol in the method name. There's no ambiguity with existing selectors in Foundation.

Rename performInteractionWithError: -> perform:

---

build.sh

The quoting means that the globbing of the artifact path fails.

Fix build.sh copying

---

fbsimctl/FBSimulatorControlKit/Sources/Events.swift
fbsimctl/FBSimulatorControlKit/Sources/Runners.swift

Calling `fbsimct all delete` on an empty pool really shouldn't error. In fact all commands that operate on an empty pool should return fine with a logger message.
Additionally, failure messages weren't sent to the reporter, which would mean that some failure messages aren't json-ified.

Don't fail on an empty pool

---

FBSimulatorControl/Management/FBSimulatorControl+PrincipalClass.h
FBSimulatorControl/Management/FBSimulatorControl+PrincipalClass.m
FBSimulatorControl/Management/FBSimulatorPool.h
FBSimulatorControl/Management/FBSimulatorPool.m
FBSimulatorControl/Management/FBSimulatorSet+Private.h
FBSimulatorControl/Management/FBSimulatorSet.h
FBSimulatorControl/Management/FBSimulatorSet.m
FBSimulatorControlTests/Tests/FBSimulatorLaunchTests.m
FBSimulatorControlTests/Tests/FBSimulatorPoolTests.m
FBSimulatorControlTests/Utilities/FBSimulatorControlTestCase.m
FBSimulatorControlTests/Utilities/FBSimulatorPoolTestCase.m
fbsimctl/FBSimulatorControlKit/Sources/Runners.swift

- Add a backreference from `FBSimulatorSet` to `FBSimulatorControl`
- Don't assert on wrong sim, return error.
- Create `FBSimulatorSet` and pass-from-above to `FBSimulatorPool`

Additional Robustness in FBSimulatorSet

---

FBSimulatorControl/Configuration/FBSimulatorLaunchConfiguration+Helpers.m
FBSimulatorControl/Management/FBSimulator+Helpers.h
FBSimulatorControl/Management/FBSimulator+Helpers.m
PrivateHeaders/CoreSimulator/SimDevice.h
fbsimctl/FBSimulatorControlKit/Sources/Runners.swift

This appears to have gone recently, it still exists on `SimDevieSet`

Fix missing -[SimDevice setPath] in Xcode 7 Betas

---

FBSimulatorControl/Configuration/FBSimulatorLaunchConfiguration.h
FBSimulatorControl/Configuration/FBSimulatorLaunchConfiguration.m
FBSimulatorControl/Framebuffer/FBFramebufferVideo.h
FBSimulatorControl/Framebuffer/FBFramebufferVideo.m
FBSimulatorControl/Framebuffer/FBSimulatorFramebuffer.m
FBSimulatorControl/Management/FBSimulatorBridge.m

The current way of creating the `SimDeviceFramebufferService` uses the `mainScreen` resolution. When recording a video, this is then thrown away and downscaled, which is a waste of resources. A 50% scale is a 4X reduction in the Framebuffer size and means less bytes are going to be copied around, leading to a lower resource utilisation on the host.

Scale at the SimDeviceFramebufferService level

---

FBSimulatorControl.xcodeproj/project.pbxproj
FBSimulatorControl/Framebuffer/FBFramebufferCompositeDelegate.m
FBSimulatorControl/Framebuffer/FBFramebufferDebugWindow.m
FBSimulatorControl/Framebuffer/FBFramebufferDelegate.h
FBSimulatorControl/Framebuffer/FBFramebufferFrame.h
FBSimulatorControl/Framebuffer/FBFramebufferFrame.m
FBSimulatorControl/Framebuffer/FBFramebufferImage.m
FBSimulatorControl/Framebuffer/FBFramebufferVideo.m
FBSimulatorControl/Framebuffer/FBSimulatorFramebuffer.m

Instead of constructing the current time of a frame at the `FBFramebufferVideo`'s `mediaQueue`, we should construct it at the time that the `FBSimulatorFramebuffer` gets the frames on it's own queue, with increased precision.
This should give a more accurate time than on the `mediaQueue`, both in terms of resolution of the time (by using a timescale that matches the system clock) and because `CMTime` values are created from the timebase when frames are pushed to the `FBSimulatorFramebuffer`'s private queue. Time conversions to a timescale more suitable for video encoding can then occur in `FBFramebufferVideo`.
Since there are a boatload of values passed around on the `FBSimulatorFramebufferDelegate` methods the params are now put inside a `FBFramebufferFrame` object. This also aids with …

Monotonic Framebuffer Frame Times

---

FBSimulatorControl/Configuration/FBSimulatorLaunchConfiguration.h
FBSimulatorControl/Framebuffer/FBFramebufferFrame.h
FBSimulatorControl/Framebuffer/FBFramebufferVideo.h
FBSimulatorControl/Framebuffer/FBFramebufferVideo.m
FBSimulatorControl/Framebuffer/FBSimulatorFramebuffer.h
FBSimulatorControl/Framebuffer/FBSimulatorFramebuffer.m
FBSimulatorControl/Utility/FBCapacityQueue.h
FBSimulatorControl/Utility/FBCapacityQueue.m

Prior to this PR, it starting and stopping of video recording was completely automatic and would be enabled/disabled per Simulator boot. This PR adds an start/stop recording API and an optional launch flag for enabling the automatic recording of video on Simulator boot.

Add Automatic and Manual Video Recording

---

FBSimulatorControl.xcodeproj/project.pbxproj
FBSimulatorControl/Configuration/FBFramebufferVideoConfiguration.h
FBSimulatorControl/Configuration/FBFramebufferVideoConfiguration.m
FBSimulatorControl/Configuration/FBSimulatorLaunchConfiguration.h
FBSimulatorControl/Configuration/FBSimulatorLaunchConfiguration.m
FBSimulatorControl/FBSimulatorControl.h
FBSimulatorControl/Framebuffer/FBFramebufferVideo.h
FBSimulatorControl/Framebuffer/FBFramebufferVideo.m
FBSimulatorControl/Framebuffer/FBSimulatorFramebuffer.m
FBSimulatorControl/Management/FBSimulatorBridge.h
FBSimulatorControl/Management/FBSimulatorBridge.m
FBSimulatorControlTests/Tests/FBFramebufferVideoConfigurationTests.m
FBSimulatorControlTests/Tests/FBSimulatorLaunchConfigurationTests.m
FBSimulatorControlTests/Utilities/FBSimulatorControlTestCase.m
fbsimctl/FBSimulatorControlKit/Sources/Command.swift
fbsimctl/FBSimulatorControlKit/Sources/CommandParsers.swift
fbsimctl/FBSimulatorControlKit/Sources/Events.swift
fbsimctl/FBSimulatorControlKit/Sources/HttpRelay.swift
fbsimctl/FBSimulatorControlKit/Sources/Runners.swift
fbsimctl/FBSimulatorControlKitTests/Tests/CommandParsersTests.swift

Sadly, it looks like there are still issues with encoding when using `AVFileTypeMPEG4`. Instead of messing around with this in master until we find the sweet spot, it makes more sense to be able to manipulate the configuration of video encoding in clients that care about this. `FBFramebufferVideoConfiguration` takes on this role.
Additionally the `--record-video` flag disappears and can be replaced with `record start` by chaining interactions in `fbsimctl`.

Add FBFramebufferVideoConfiguration

---

FBSimulatorControl.xcodeproj/project.pbxproj
FBSimulatorControl/FBSimulatorControl.h
FBSimulatorControl/Framebuffer/FBFramebuffer.h
FBSimulatorControl/Framebuffer/FBFramebuffer.m
FBSimulatorControl/Framebuffer/FBFramebufferCompositeDelegate.m
FBSimulatorControl/Framebuffer/FBFramebufferDebugWindow.m
FBSimulatorControl/Framebuffer/FBFramebufferDelegate.h
FBSimulatorControl/Framebuffer/FBFramebufferImage.m
FBSimulatorControl/Framebuffer/FBFramebufferVideo.m
FBSimulatorControl/Interactions/FBSimulatorInteraction+Lifecycle.m
FBSimulatorControl/Management/FBSimulatorBridge.h
FBSimulatorControl/Management/FBSimulatorBridge.m

All the the other Frambuffer classes (including the delegate) begin with `FBFramebuffer` so the container object should too.

Rename FBSimulatorFramebuffer to FBFramebuffer

---

fbsimctl/FBSimulatorControlKit/Sources/HttpRelay.swift
fbsimctl/FBSimulatorControlKit/Sources/JSON.swift

Having separate endpoints for each action seems a little sad, so we can now parse numbers as bools and use this to flip the `Action.Record` action.
`NSJSONSerialization` represents Bools as `NSNumber` so all numbers can be interpreted as bools :/

Record Start/Stop of video with JSON Payload

---

FBSimulatorControl/Configuration/FBFramebufferVideoConfiguration.h
FBSimulatorControl/Configuration/FBFramebufferVideoConfiguration.m
FBSimulatorControl/Framebuffer/FBFramebufferVideo.h
FBSimulatorControl/Framebuffer/FBFramebufferVideo.m
FBSimulatorControl/Interactions/FBSimulatorInteraction+Lifecycle.h
FBSimulatorControl/Interactions/FBSimulatorInteraction+Lifecycle.m
FBSimulatorControlTests/Tests/Unit/FBConfigurationTests.m
FBSimulatorControlTests/Utilities/FBSimulatorControlTestCase.m
fbsimctl/FBSimulatorControlKit/Sources/Runners.swift

There are a number of optional behaviours in `FBFramebufferVideo` that can be switched on and off independently, so they have been given an option Set.
- `FBFramebufferVideoOptionsAutorecord` takes the place of the `autorecord` BOOl on `FBFramebufferConfiguration`
- `FBFramebufferVideoOptionsImmediateFrameStart` will cause the prior frame event to be kept around so that the record can start 'immediately'. The reason for doing this is that if the Simulator is at the home screen the first frame that will be received after the 'waiting for frame' state is set will be changes to the clock (i.e. once per minute) since Springboard doesn't need to redraw until the clock changes.
- `FBFramebufferVideoOptionsFinalFrame` is like the above, but upon stopping the video. By re-pushing the last frame …

Add FBFramebufferVideoOptions

---

FBSimulatorControl.xcodeproj/project.pbxproj
FBSimulatorControl/Diagnostics/FBDiagnostic.h
FBSimulatorControl/Diagnostics/FBDiagnostic.m
FBSimulatorControlTests/Fixtures/FBSimulatorControlFixtures.h
FBSimulatorControlTests/Fixtures/FBSimulatorControlFixtures.m
FBSimulatorControlTests/Fixtures/simulator_system.log
FBSimulatorControlTests/Fixtures/tree.json
FBSimulatorControlTests/Tests/Unit/FBDiagnosticTests.m

JSON is used throughout `FBSimulatorControl` and is used widely for wiring data around in a structured way. For example the `tree` command on `WebDriverAgent` produces a JSON Tree of the element hierarchy. This is very helpful for diagnosing common issues when running end-to-end tests with `WebDriverAgent`. By being able to treat this as a 'Diagnostic' it becomes easier to shuffle it around.

FBDiagnostic with bi-directional JSON Coercions
