facebook/FBSimulatorControl

README.md
=> fix code example so it works

FBSimulatorControl/Management/FBSimulatorPool.m
Simulators aren't being configured properly in the happy path due to early-return. This means that the locale of the Simulator won't always be set.
=> Simulator preparation happy path should perform all steps

FBSimulatorControl/Logs/FBSimulatorLogs.m, FBSimulatorControlTests/Tests/FBSimulatorLogsTests.m
Actually fetches the syslog from the appropriate path. Adds a test.
=> Add System Log Fetching w/ Test

FBSimulatorControl/Tiling/FBSimulatorWindowHelpers.h, FBSimulatorControl/Tiling/FBSimulatorWindowHelpers.m
=> Add Debug Description for Displays

FBSimulatorControl/Management/FBSimulator+Private.h, FBSimulatorControl/Management/FBSimulator.h, FBSimulatorControl/Management/FBSimulator.m, FBSimulatorControl/Management/FBSimulatorLaunchInfo.h, FBSimulatorControl/Management/FBSimulatorLaunchInfo.m, FBSimulatorControl/Management/FBSimulatorPool+Private.h, FBSimulatorControl/Management/FBSimulatorPool.h, FBSimulatorControl/Management/FBSimulatorPool.m, FBSimulatorControl/Management/FBSimulatorTerminationStrategy.h, FBSimulatorControl/Management/FBSimulatorTerminationStrategy.m, FBSimulatorControl/Notifications/FBDispatchSourceNotifier.h, FBSimulatorControl/Session/FBSimulatorSession.m, FBSimulatorControl/Session/FBSimulatorSessionLifecycle.h, FBSimulatorControl/Session/FBSimulatorSessionLifecycle.m, FBSimulatorControl/Tiling/FBSimulatorWindowHelpers.h, FBSimulatorControl/Tiling/FBSimulatorWindowHelpers.m, FBSimulatorControlTests/Tests/FBSimulatorControlApplicationLaunchTests.m, FBSimulatorControlTests/Tests/FBSimulatorControlSimulatorLaunchTests.m, FBSimulatorControlTests/Tests/FBSimulatorPoolAllocationTests.m, FBSimulatorControlTests/Tests/FBSimulatorPoolTests.m, FBSimulatorControlTests/Utilities/FBSimulatorControlAssertions.m, fbsimctl/Sources/Command.swift, fbsimctl/Sources/Runners.swift
Moves Simulator Launch notifications to the appropriate place; the Simulator.
=> Simulator Launch Notification

FBSimulatorControl.xcodeproj/project.pbxproj, FBSimulatorControl/Configuration/FBProcessLaunchConfiguration+Helpers.h, FBSimulatorControl/Configuration/FBProcessLaunchConfiguration.h, FBSimulatorControl/Configuration/FBProcessLaunchConfiguration.m, FBSimulatorControl/Configuration/FBSimulatorConfiguration+Private.h, FBSimulatorControl/Configuration/FBSimulatorConfiguration.h, FBSimulatorControl/Configuration/FBSimulatorConfiguration.m, FBSimulatorControl/Configuration/FBSimulatorControlConfiguration.h, FBSimulatorControl/Configuration/FBSimulatorControlConfiguration.m, FBSimulatorControl/Model/FBSimulatorApplication.h, FBSimulatorControl/Model/FBSimulatorApplication.m, FBSimulatorControlTests/Tests/FBProcessLaunchConfigurationTests.m, FBSimulatorControlTests/Tests/FBSimulatorConfigurationTests.m, FBSimulatorControlTests/Tests/FBSimulatorControlConfigurationTests.m
This enables serialization of configurations so that they can be read cross-process.
=> Add NSCoding to Configurations

FBSimulatorControl/Model/FBSimulatorApplication.m
Binary name may differ from application name, fetching from Info.plist instead.
=> Getting binary name from Info.plist file

FBSimulatorControl.xcodeproj/project.pbxproj, FBSimulatorControl/Configuration/FBSimulatorControlConfiguration.h, FBSimulatorControl/Management/FBSimulatorInteraction+Agents.m, FBSimulatorControl/Management/FBSimulatorInteraction+Applications.m, FBSimulatorControl/Utility/FBSimDeviceWrapper.h, FBSimulatorControl/Utility/FBSimDeviceWrapper.m
Could be that this value is too low on the VM'd travis machines. This allows the timeout to be optional.
cc @mmmulani
=> Make SimDevice Timeout Optional

FBSimulatorControl/Management/FBSimulatorInteraction+Upload.m, FBSimulatorControl/Model/FBSimulatorApplication.h, FBSimulatorControl/Model/FBSimulatorApplication.m, FBSimulatorControlTests/Fixtures/FBSimulatorControlFixtures.h, FBSimulatorControlTests/Fixtures/FBSimulatorControlFixtures.m, FBSimulatorControlTests/Tests/FBProcessLaunchConfigurationTests.m, FBSimulatorControlTests/Tests/FBSimulatorApplicationTests.m, FBSimulatorControlTests/Tests/FBSimulatorControlApplicationLaunchTests.m, FBSimulatorControlTests/Tests/FBSimulatorLogsTests.m, FBSimulatorControlTests/Tests/FBSimulatorSessionLifecycleTests.m, FBSimulatorControlTests/Tests/FBSimulatorStateTests.m, FBSimulatorControlTests/Tests/FBSimulatorVideoRecorderTests.m
In #95 I'm having difficulty diagnosing why some of the App Launches are failing, this should help diagnose the callsite that is likely failing.
=> Improve App Launch Fixtures & Error Handling

FBSimulatorControl/Logs/FBSimulatorLogs.m, FBSimulatorControl/Model/FBSimulatorHistory+Queries.h, FBSimulatorControl/Model/FBSimulatorHistory+Queries.m
=> Don't include Agents with .app in name in Launched Application list

FBSimulatorControl/Management/FBSimulatorTerminationStrategy.m, FBSimulatorControl/Utility/FBSimulatorError.h, FBSimulatorControl/Utility/FBSimulatorError.m
Error messaging on termination can be somewhat cryptic, this should fix that.
=> Additional Error Messaging when failing to kill processes.

FBSimulatorControl/Configuration/FBSimulatorControlStaticConfiguration.h, FBSimulatorControl/Configuration/FBSimulatorControlStaticConfiguration.m
=> Verify that Developer Directory matches preloaded Frameworks

FBSimulatorControl/Management/FBSimulatorTerminationStrategy.m
=> Force Terminate on NSRunningApplication

.travis.yml
This should work fine as I've been developing locally with it
=> Enable Xcode 7.2 on Travis

fbsimctl/FBSimulatorControlKit/Sources/CommandParsers.swift, fbsimctl/FBSimulatorControlKit/Sources/Parser.swift, fbsimctl/FBSimulatorControlKitTests/Tests/CommandParsersTest.swift
Configuration Values need some love for tests too.
=> Tests for Configuration Parsers

fbsimctl/FBSimulatorControlKit/Sources/Relay.swift, fbsimctl/FBSimulatorControlKit/Sources/Runners.swift
Sequencing `Runner`s now has a common implementation so that sequencing the running of Simulators and of Actions behaves in the same way.
=> Sequence Runner

FBSimulatorControl/Configuration/FBSimulatorConfiguration+Private.h, FBSimulatorControl/Configuration/FBSimulatorConfiguration.h, FBSimulatorControl/Configuration/FBSimulatorConfiguration.m
- iOS 9.3
- watchOS 2.2
- tvOS 9.2
=> Xcode 7.3 OS Versions

fbsimctl/FBSimulatorControlKit/Sources/Command.swift, fbsimctl/FBSimulatorControlKit/Sources/CommandParsers.swift, fbsimctl/FBSimulatorControlKit/Sources/Runners.swift, fbsimctl/FBSimulatorControlKitTests/Tests/CommandParsersTests.swift
- `--state`: The State of the Simulator
- `--pid`: The process identifier of the `launchd_sim`
=> Add Formats to CLI

fbsimctl/FBSimulatorControlKit/Sources/CommandParsers.swift, fbsimctl/FBSimulatorControlKit/Sources/Parser.swift, fbsimctl/FBSimulatorControlKitTests/Tests/CommandParsersTests.swift
Any arguments at the end of the `launch` interaction will be placed in the launch configuration.
=> Arguments to launched process in the Launch Command

FBSimulatorControl.xcodeproj/project.pbxproj, FBSimulatorControl/Configuration/FBSimulatorLaunchConfiguration+Private.h, FBSimulatorControl/Configuration/FBSimulatorLaunchConfiguration.m, FBSimulatorControl/FBSimulatorControl.h, FBSimulatorControl/Interactions/FBSimulatorInteraction+Setup.h, FBSimulatorControl/Interactions/FBSimulatorInteraction+Setup.m, fbsimctl/FBSimulatorControlKit/Sources/Command.swift, fbsimctl/FBSimulatorControlKit/Sources/CommandParsers.swift, fbsimctl/FBSimulatorControlKit/Sources/Runners.swift, fbsimctl/FBSimulatorControlKitTests/Tests/CommandParsersTests.swift
=> Approve Location Services for Application

FBSimulatorControl/Management/FBSimulator+Helpers.m
Saves pulling down a massive dictionary.
=> Use propertiesOfApplication instead of installedApps

FBSimulatorControl/Interactions/FBSimulatorInteraction.m
Fixing error string to correctly report both the actual and expected state of the simulator
=> Fixing error string

FBSimulatorControl.xcodeproj/project.pbxproj, FBSimulatorControl/Events/FBMutableSimulatorEventSink.h, FBSimulatorControl/Events/FBMutableSimulatorEventSink.m, FBSimulatorControl/FBSimulatorControl.h, FBSimulatorControl/Management/FBSimulator+Private.h, FBSimulatorControl/Management/FBSimulator.h, FBSimulatorControl/Management/FBSimulator.m, fbsimctl/FBSimulatorControlKit/Sources/Command.swift, fbsimctl/FBSimulatorControlKit/Sources/CommandParsers.swift, fbsimctl/FBSimulatorControlKit/Sources/Defaults.swift, fbsimctl/FBSimulatorControlKit/Sources/EventReporter.swift, fbsimctl/FBSimulatorControlKit/Sources/JSON.swift, fbsimctl/FBSimulatorControlKit/Sources/Runners.swift, fbsimctl/FBSimulatorControlKitTests/Tests/CommandParsersTests.swift, fbsimctl/fbsimctl.xcodeproj/project.pbxproj, fbsimctl/fbsimctl.xcodeproj/xcshareddata/xcschemes/fbsimctl.xcscheme
=> Full JSON Output CLI

FBSimulatorControl/Interactions/FBSimulatorInteraction+Setup.m
There's a bunch of methods that have a common way of updating/creating a plist, so this should be pulled out into a helper method.
@mmmulani you may want to check the `FBLaunchWatchdogExceptions` value, it looks like the old implementation will just overrwrite the value with the last item in the array, I think this fixes that.
=> Utility method for updating a plist in place

FBSimulatorControl/Management/FBSimulatorPool.m
This was previously using the wrong option set.
=> Use appropriate option set for FBSimulatorAllocationOptionsEraseOnFree

FBSimulatorControl/Framebuffer/FBFramebufferVideo.m
When flushing the video's buffer, it can look like the video is cut short if the simulator doesn't redraw for some time. When tearing down the Video writer, we now re-push the last frame with the current time to make this idleness obvious in the video.
=> Repush the last video frame at Current Time

FBSimulatorControl/Framebuffer/FBFramebufferVideo.m
Helps figure out any races in the teardown path.
=> Additional logging for video

.travis.yml, build.sh
Adds archiving and uses `xcodebuild` for building, so this should help out the homebrew/deploy case.
=> Improve the build.sh

build.sh
Support automation by making build.sh complain if something goes wrong.
=> [build] Build script now throws non-zero on error

fbsimctl/FBSimulatorControlKit/Sources/Command.swift, fbsimctl/FBSimulatorControlKit/Sources/CommandParsers.swift, fbsimctl/FBSimulatorControlKit/Sources/CommandPerformer.swift, fbsimctl/FBSimulatorControlKit/Sources/Defaults.swift, fbsimctl/FBSimulatorControlKit/Sources/EventReporter.swift, fbsimctl/FBSimulatorControlKit/Sources/HttpRelay.swift, fbsimctl/FBSimulatorControlKit/Sources/Parser.swift, fbsimctl/FBSimulatorControlKit/Sources/Relay.swift, fbsimctl/FBSimulatorControlKit/Sources/Runners.swift, fbsimctl/FBSimulatorControlKit/Sources/SocketRelay.swift, fbsimctl/FBSimulatorControlKit/Sources/StdIORelay.swift, fbsimctl/FBSimulatorControlKitTests/Tests/CommandParsersTests.swift, fbsimctl/fbsimctl.xcodeproj/project.pbxproj, fbsimctl/fbsimctl/main.swift
`Parsable` is a protocol for providing a parser of a specific type. This was previously provided by a static method, but since swift supports static vars it makes more sense to use those.
=> Parsable as a Property

FBSimulatorControl.xcodeproj/project.pbxproj, FBSimulatorControl/Framebuffer/FBFramebufferCompositeDelegate.m, FBSimulatorControl/Framebuffer/FBFramebufferDebugWindow.m, FBSimulatorControl/Framebuffer/FBFramebufferDelegate.h, FBSimulatorControl/Framebuffer/FBFramebufferFrame.h, FBSimulatorControl/Framebuffer/FBFramebufferFrame.m, FBSimulatorControl/Framebuffer/FBFramebufferImage.m, FBSimulatorControl/Framebuffer/FBFramebufferVideo.m, FBSimulatorControl/Framebuffer/FBSimulatorFramebuffer.m
Depending on #229, running the tests to confirm that the reliability of video encoding has improved now there is timebase conversion in #229.
=> Use MPEG4 Container

FBSimulatorControl.xcodeproj/project.pbxproj
For some reason this was unlinked, causing some code signing issues.
=> Linking Info.plist to main framework target

FBSimulatorControl/Diagnostics/FBDiagnostic.m
=> Add Path Extension to File Diagnostics

fbsimctl/FBSimulatorControlKit/Sources/Runners.swift
All Actions will now report start/end events to the `EventReporter`, this previously was defined per-action. Additionally each diagnostic is a separate event rather than a single event with an array subject, removing one level of nesting.
=> Common start/end events for all actions

FBSimulatorControl/Diagnostics/FBDiagnostic.m, FBSimulatorControlTests/Tests/Unit/FBDiagnosticTests.m
There was a case for `FBDiagnostic` writing that meant that new data in old paths could result in the old data staying, so this has been fixed along with some unit tests for these cases.
=> Fix FBDiagnostic File Writing
